Repository submariner-io/submariner, pull requests merged in 2020-11, with the labels that each got.

#916 Add CI for CODEOWNERS generation
  .github/workflows/codeowners.yml
Labels: automation

#904 Libreswan 4
  pkg/cable/libreswan/libreswan.go
Labels: libreswan

#917 Use single space vs tab alignment in CODEOWNERS.in
  CODEOWNERS.in
Labels: automation

#920 Remove master branch filter from badge links
  README.md
Labels: docs

#972 Use Libreswan by default
  pkg/cable/libreswan/libreswan.go
  pkg/cable/strongswan/strongswan.go
  pkg/util/util_test.go
Labels: libreswan
