Repository submariner-io/submariner, pull requests merged in 2020-04, with the labels that each got.

#402 Modify StringSet.Delete to return if found
  pkg/routeagent/controllers/route/route.go
  pkg/util/stringset.go
  pkg/util/stringset_test.go
Labels: technical-debt

#487 Remove status flag from E2E
  .travis.yml
  Makefile
  README.md
  docs/contributing.md
  docs/testing.md
  scripts/kind-e2e/README.md
  scripts/kind-e2e/e2e.sh
Labels: automation, shipyard

#351 Re-enable and fix Gateway failover tests
  test/e2e/redundancy/gateway_failover.go
Labels: automation, backport, bug, technical-debt

#511 Remove load_deploytool
  Makefile
  scripts/kind-e2e/e2e.sh
Labels: automation, shipyard
