Repository submariner-io/submariner, pull requests merged in 2020-03, with the labels that each got.

#401 Check LinkNotFoundError in cleanVxSubmarinerRoutes
  pkg/routeagent/controllers/route/route.go
Labels: technical-debt

#400 Cleanup how CI jobs deploy artifacts after success
  .travis.yml
Labels: automation, bug

#413 Fix Travis env var syntax
  .travis.yml
Labels: bug

#408 Fix race loop when ClusterCRD is updated with globalCIDR
  go.mod
  pkg/datastore/kubernetes/kubernetes.go
Labels: bug

#418 Fix CI deploy
  .travis.yml
  scripts/release
Labels: backport

#410 Use DEBUG/TRACE levels in globalnet
  pkg/globalnet/controllers/ipam/gatewaymonitor.go
  pkg/globalnet/controllers/ipam/globalnet.go
  pkg/globalnet/controllers/ipam/globalnet_egress.go
  pkg/globalnet/controllers/ipam/globalnet_ingress.go
  pkg/globalnet/controllers/ipam/ipam.go
  pkg/globalnet/main.go
  pkg/routeagent/main.go
Labels: technical-debt

#411 Remove unused functions in Datastore interface
  pkg/datastore/datastore.go
  pkg/datastore/kubernetes/kubernetes.go
  pkg/datastore/phpapi/phpapi.go
Labels: technical-debt

#349 Refactoring for support pluggable drivers.
  main.go
  pkg/cable/driver.go
  pkg/cable/ipsec/strongswan.go
  pkg/cable/ipsec/strongswan_test.go
  pkg/cableengine/cableengine.go
  pkg/cableengine/ipsec/driver.go
  pkg/cableengine/ipsec/ipsec.go
  pkg/types/types.go
Labels: enhancement

#403 Refactor handleRemovedEndpoint
  pkg/routeagent/controllers/route/route.go
Labels: technical-debt

#423 Use getopt for robust params in e2e.sh
  Makefile
  scripts/build
  scripts/build-engine
  scripts/build-globalnet
  scripts/build-routeagent
  scripts/ci
  scripts/kind-e2e/e2e.sh
Labels: armada, automation

#419 Use portable paths for kind-e2e files
  scripts/kind-e2e/README.md
  scripts/kind-e2e/e2e.sh
Labels: automation, shipyard

#409 Copy e2e scripts into container for sharing
  package/Dockerfile.dapper-base
  scripts/e2e
Labels: automation
