Repository submariner-io/submariner, pull requests merged in 2020-10, with the labels that each got.

#862 Don't run linting on tags
  .github/workflows/linting.yml
Labels: automation, bug

#863 Stop using the WireGuard PPA
  .github/workflows/e2e.yml
Labels: automation, testing

#865 Don't run unit or E2E tests on tags
  .github/workflows/e2e.yml
  .github/workflows/unit.yml
Labels: automation

#881 Parameters for prep script
  tools/openshift/ocp-ipi-aws/README.md
  tools/openshift/ocp-ipi-aws/main.tf
  tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/ec2-resources.tf
  tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/machine-set-resources.tf
  tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/templates/machine-set.yaml
  tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/variables.tf
  tools/openshift/ocp-ipi-aws/prep_for_subm.sh
Labels: bug

#898 Remove unused architecture docs images
  docs/img/architecture.jpg
  docs/img/architecture.png
Labels: cncf, docs

#897 De-duplicate testing docs
  docs/testing.md
Labels: cncf, docs

#845 Add GatewaySyncer metrics
  pkg/cableengine/syncer/syncer.go
Labels: metrics

#909 Add CODE-OF-CONDUCT.md, point to website
  CODE-OF-CONDUCT.md
Labels: cncf, docs
