Repository submariner-io/submariner, pull requests merged in 2020-12, with the labels that each got.

#846 Track RX/TX bytes in the Libreswan cable driver
  pkg/cable/libreswan/libreswan.go
Labels: libreswan, metrics

#978 Record connection latency metric
  pkg/cable/metrics.go
  pkg/cableengine/syncer/syncer.go
Labels: metrics

#1006 Document the use of port 8080 in the OCS-IPI README
  tools/openshift/ocp-ipi-aws/README.md
Labels: docs

#1007 Fix testing Libreswan twice and strongSwan none
  .github/workflows/e2e.yml
  .github/workflows/periodic_e2e.yml
Labels: automation

#963 Remove cable driver using= flag, use Shipyard's
  Makefile
Labels: automation

#1025 Insert MSS clamping for traffic arriving services
  pkg/routeagent_driver/handlers/ovn/gateway_dataplane.go
Labels: OVN, blocker, datapath

#1028 Associate submariner_router to chassis via options
  pkg/networkplugin-syncer/handlers/ovn/handler.go
  pkg/networkplugin-syncer/handlers/ovn/nbctl/nbctl.go
  pkg/networkplugin-syncer/handlers/ovn/router_ovn_cluster_north.go
  pkg/networkplugin-syncer/handlers/ovn/router_submariner_south.go
Labels: OVN, blocker, bug, datapath

#1035 Increase upgrade test timeout 30->45 mins
  .github/workflows/upgrade-e2e.yml
Labels: automation

#814 Fail codegen "validation" if it caused a change
  .github/workflows/linting.yml
Labels: automation

#1043 Update gitlint ignore for new Dependabot
  .gitlint
Labels: automation

#1053 Support non non ssl connections for ovn-kubernetes database
  pkg/networkplugin-syncer/handlers/ovn/connection.go
  pkg/networkplugin-syncer/handlers/ovn/nbctl/nbctl.go
Labels: OVN, automation

#1052 Fix cable driver in connection latency metric
  pkg/cableengine/syncer/syncer.go
Labels: metrics

#899 Adding wireguard prometheus metrics
  pkg/cable/metrics.go
  pkg/cable/wireguard/README.md
  pkg/cable/wireguard/driver.go
  pkg/cable/wireguard/getconnections.go
Labels: metrics, wireguard
