Repository submariner-io/submariner, pull requests merged in 2021-04, with the labels that each got.

#1242 Update K8s default to 1.20, also test 1.17
  .github/workflows/e2e.yml
Labels: automation

#1245 Start pinger only in active g/w pod
  main.go
Labels: bug

#1246 Make the API additions in 0.9 optional to fix upgrades
  pkg/apis/submariner.io/v1/types.go
Labels: blocker, upgrade

#1248 Fix the default SKIP regex for E2E ginkgo
  Makefile
Labels: upgrade

#1263 Stop adding the endpoint PrivateIP/32 to the subnet list in libreswan
  pkg/cable/libreswan/libreswan.go
Labels: blocker, bug, datapath

#1267 Fix issue with g/w with status message
  pkg/cableengine/syncer/syncer.go
Labels: bug

#1285 Create br-submariner in each worker node for OVN to use
  pkg/routeagent_driver/handlers/ovn/bridge.go
  pkg/routeagent_driver/handlers/ovn/constants.go
  pkg/routeagent_driver/handlers/ovn/handler.go
  pkg/routeagent_driver/handlers/ovn/host_networking.go
  pkg/routeagent_driver/handlers/ovn/vsctl/vsctl.go
Labels: 0.9.0-testday, OVN, bug

#1286 Refactor the OVN support to make it more implementation idependent
  go.mod
  go.sum
  pkg/networkplugin-syncer/handlers/ovn/handler.go
  pkg/networkplugin-syncer/handlers/ovn/infrastructure.go
  pkg/networkplugin-syncer/handlers/ovn/ovn_kubernetes_versions.go
  pkg/networkplugin-syncer/handlers/ovn/router_ovn_cluster_north.go
  pkg/networkplugin-syncer/handlers/ovn/router_submariner_north.go
  pkg/networkplugin-syncer/handlers/ovn/router_submariner_south.go
  pkg/routeagent_driver/handlers/ovn/bridge.go
  pkg/routeagent_driver/handlers/ovn/constants.go
  pkg/routeagent_driver/handlers/ovn/gateway_dataplane.go
  pkg/routeagent_driver/handlers/ovn/handler.go
  scripts/reload-images
Labels: 0.9.0-testday, OVN, blocker, bug

#1287 Fix flaky errors with Globalnet CI jobs
  go.mod
  go.sum
Labels: testing

#1292 Disable the DCO GHA
  .github/workflows/linting.yml
Labels: cncf

#1294 MSS clamping for outgoing TCP packets with OVN
  pkg/routeagent_driver/handlers/ovn/gateway_dataplane.go
Labels: 0.9.0-testday, OVN, blocker, bug, datapath

#1296 Add MSS clamping to the OUTPUT chain on the gateway
  pkg/routeagent_driver/handlers/ovn/gateway_dataplane.go
Labels: OVN, bug, datapath
