Repository submariner-io/submariner, pull requests merged in 2021-12, with the labels that each got.

#1604 Add metrics to Globalnet 2.0
  pkg/globalnet/metrics/metrics.go
  pkg/ipam/ippool.go
Labels: ready-to-test

#1609 Fix issue with gateway name in e2e
  test/e2e/redundancy/gateway_failover.go
Labels: ready-to-test

#1607 Formalize local build settings
  Makefile
Labels: ready-to-test

#1613 Drop obsolete security replaces
  go.mod
  go.sum
Labels: ready-to-test

#1616 Add ADOPTERS.md file, add Red Hat
  ADOPTERS.md
Labels: docs, ready-to-test

#1621 Move the netlink dependency out of util
  pkg/cable/vxlan/vxlan.go
  pkg/netlink/netlink.go
  pkg/routeagent_driver/handlers/kubeproxy/kp_iptables.go
  pkg/routeagent_driver/handlers/kubeproxy/sync_handler_test.go
  pkg/routeagent_driver/handlers/ovn/handler.go
  pkg/util/util.go
Labels: ready-to-test

#1617 Add PR reviews link to committer request template
  .github/ISSUE_TEMPLATE/committership.md
Labels: docs, ready-to-test

#1624 Add dfarrell07 as *.md code owner
  CODEOWNERS
  CODEOWNERS.in
Labels: ready-to-test

#1612 Merge the api module back into the main module
  .lichen.yaml
  Makefile
  go.mod
  go.sum
  pkg/apis/LICENSE
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/apis/submariner.io/v1/register.go
  pkg/apis/submariner.io/v1/string_test.go
  pkg/apis/submariner.io/v1/types.go
  pkg/cable/wireguard/driver.go
Labels: ready-to-test

#1629 Fix intermittent pinger test failures
  pkg/cableengine/healthchecker/pinger_test.go
Labels: ready-to-test

#1626 Handle secrets for broker access in the gateway
  go.mod
  go.sum
Labels: ready-to-test

#1623 Add GHA for SubM Tweeting via PRs
  .github/workflows/twitter-together.yml
Labels: docs, automation, ready-to-test

#1639 Globalnet fix for issues with multiple headless svs
  pkg/globalnet/controllers/base_controllers.go
  pkg/globalnet/controllers/ingress_pod_controller.go
  pkg/globalnet/controllers/service_controller.go
  pkg/globalnet/controllers/service_export_controller.go
Labels: backport, ready-to-test

#1640 Globalnet fix for issues with multiple headless svs
  pkg/globalnet/controllers/base_controllers.go
  pkg/globalnet/controllers/ingress_pod_controller.go
  pkg/globalnet/controllers/service_controller.go
  pkg/globalnet/controllers/service_export_controller.go
Labels: ready-to-test
