Repository submariner-io/submariner, pull requests merged in 2021-05, with the labels that each got.

#1300 Bump dependencies
  go.mod
  go.sum
Labels: dependencies

#1316 Fix intermittent data race failure in pinger
  pkg/cableengine/healthchecker/pinger.go
Labels: backport-handled

#1343 Add CII badge, remove PR-triggered badges
  README.md
Labels: cncf, docs

#1342 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cncf, docs

#1324 Run full E2E matrix only when PR approved
  .github/workflows/e2e-full.yml
  .github/workflows/e2e.yml
Labels: ready-to-test

#1338 Add GlobalIngressIP CRD and related generated code
  pkg/apis/submariner.io/v1/register.go
  pkg/apis/submariner.io/v1/types.go
  pkg/apis/submariner.io/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/fake/fake_globalingressip.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/fake/fake_submariner.io_client.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/globalingressip.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/submariner.io_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/submariner.io/v1/globalingressip.go
  pkg/client/informers/externalversions/submariner.io/v1/interface.go
  pkg/client/listers/submariner.io/v1/expansion_generated.go
  pkg/client/listers/submariner.io/v1/globalingressip.go
Labels: ready-to-test

#1349 Document that Submariner is a CNCF sandbox project
  README.md
Labels: cncf, docs, ready-to-test

#1344 Implement multiple public IP resolvers
  go.mod
  go.sum
  main.go
  pkg/apis/submariner.io/v1/types.go
  pkg/endpoint/local_endpoint.go
  pkg/endpoint/local_endpoint_test.go
  pkg/endpoint/public_ip.go
  pkg/endpoint/public_ip_test.go
  pkg/node/node.go
Labels: backport, ready-to-test

#1350 Backport: Implement multiple public IP resolvers
  go.mod
  go.sum
  main.go
  pkg/apis/submariner.io/v1/types.go
  pkg/endpoint/local_endpoint.go
  pkg/endpoint/local_endpoint_test.go
  pkg/endpoint/public_ip.go
  pkg/endpoint/public_ip_test.go
  pkg/node/node.go
Labels: ready-to-test

#1353 Allow the use of annotations to configure gateways
  pkg/apis/submariner.io/v1/types.go
  pkg/endpoint/local_endpoint.go
  pkg/endpoint/public_ip.go
Labels: ready-to-test

#1355 Add bot config for labelling when approved
  .submarinerbot.yaml
Labels: ready-to-test

#1326 Add a license-checking job
  .github/workflows/linting.yml
  .lichen.yaml
  Dockerfile.dapper
  Makefile
Labels: ready-to-test

#1327 Add GOVERNANCE.md, answer open gov checklist
  GOVERNANCE.md
Labels: cncf, docs, ready-to-test

#1354 Make Network Plugin names constants and add Calico cni
  pkg/event/registry_test.go
  pkg/networkplugin-syncer/handlers/ovn/handler.go
  pkg/networkplugin-syncer/main.go
  pkg/routeagent_driver/constants/constants.go
  pkg/routeagent_driver/handlers/kubeproxy/kp_iptables.go
  pkg/routeagent_driver/handlers/ovn/handler.go
  pkg/routeagent_driver/main.go
Labels: ready-to-test

#1345 Refactor cleanup handler for cabledrivers
  pkg/cable/cleanup/default_cleanup.go
  pkg/cable/cleanup/route_cleanup_handler.go
  pkg/event/handler.go
  pkg/globalnet/cleanup/gn_cleanup.go
  pkg/globalnet/controllers/ipam/gatewaymonitor.go
  pkg/routeagent_driver/cabledriver/xfrm_cleanup_handler.go
  pkg/routeagent_driver/cleanup/cleanup.go
  pkg/routeagent_driver/cleanup/fake/cleanup.go
  pkg/routeagent_driver/handlers/kubeproxy/cleanup_handling.go
  pkg/routeagent_driver/handlers/kubeproxy/gw_transition.go
  pkg/routeagent_driver/handlers/kubeproxy/kp_iptables.go
  pkg/routeagent_driver/handlers/kubeproxy/sync_handler_test.go
  pkg/routeagent_driver/handlers/ovn/gateway_dataplane.go
  pkg/routeagent_driver/handlers/ovn/handler.go
  pkg/routeagent_driver/main.go
Labels: ready-to-test, vxlan

#1367 Configure shortnames and scope for GN CRDS
  pkg/apis/submariner.io/v1/types.go
Labels: globalnet, ready-to-test

#1361 Don't run E2E on push
  .github/workflows/release.yml
Labels: ready-to-test

#1363 Add Globalnet v2 gateway monitor
  pkg/globalnet/controllers/cluster_egressip_controller.go
  pkg/globalnet/controllers/controllers_suite_test.go
  pkg/globalnet/controllers/gateway_monitor.go
  pkg/globalnet/controllers/gateway_monitor_test.go
  pkg/globalnet/controllers/global_egressip_controller.go
  pkg/globalnet/controllers/types.go
Labels: ready-to-test
