Repository submariner-io/submariner, pull requests merged in 2021-07, with the labels that each got.

#1446 Ignore protobuf and document entries
  .github/dependabot.yml
Labels: ready-to-test

#1448 Make IP field in globalIngressIP printable
  pkg/apis/submariner.io/v1/types.go
  pkg/natdiscovery/proto/natdiscovery.pb.go
Labels: ready-to-test

#1444 Datapath support for GlobalEgressIPs
  go.mod
  pkg/globalnet/controllers/base_controllers.go
  pkg/globalnet/controllers/cluster_egressip_controller.go
  pkg/globalnet/controllers/controllers_suite_test.go
  pkg/globalnet/controllers/egress_pod_watcher.go
  pkg/globalnet/controllers/global_egressip_controller.go
  pkg/globalnet/controllers/iptables/iface.go
  pkg/globalnet/controllers/types.go
  pkg/ipset/fake/ipset.go
  pkg/ipset/ipset.go
  pkg/ipset/types.go
Labels: ready-to-test

#1451 Set min/max limits for num of Egress IPs
  pkg/apis/submariner.io/v1/types.go
Labels: ready-to-test

#1453 Fix race condition in globalEgressIPController tests
  pkg/globalnet/controllers/egress_pod_watcher.go
  pkg/globalnet/controllers/global_egressip_controller.go
  pkg/globalnet/controllers/types.go
  pkg/ipset/named.go
Labels: ready-to-test

#1441 Ensure we use the expected protoc-gen-go
  Makefile
  pkg/natdiscovery/proto/natdiscovery.pb.go
Labels: ready-to-test

#1449 Upgrade to protobuf 1.27.1
  go.mod
  go.sum
  pkg/natdiscovery/proto/natdiscovery.pb.go
Labels: ready-to-test

#1423 Retry the lookup for the loadbalancer before exiting
  pkg/endpoint/public_ip.go
Labels: ready-to-test

#1452 Export GOPATH in codegen
  scripts/codegen
Labels: ready-to-test

#1445 Add shared ingress pod controllers
  pkg/globalnet/controllers/controllers_suite_test.go
  pkg/globalnet/controllers/gateway_monitor.go
  pkg/globalnet/controllers/gateway_monitor_test.go
  pkg/globalnet/controllers/ingress_pod_controller.go
  pkg/globalnet/controllers/ingress_pod_controllers.go
  pkg/globalnet/controllers/service_controller.go
  pkg/globalnet/controllers/service_controller_test.go
  pkg/globalnet/controllers/service_export_controller.go
  pkg/globalnet/controllers/service_export_controller_test.go
  pkg/globalnet/controllers/types.go
Labels: ready-to-test

#1456 Datapath support for headless services
  pkg/globalnet/controllers/global_ingressip_controller.go
  pkg/globalnet/controllers/ingress_pod_controller.go
  pkg/globalnet/controllers/iptables/iface.go
  pkg/globalnet/controllers/service_export_controller.go
  pkg/globalnet/controllers/types.go
Labels: globalnet, ready-to-test

#1460 Egress datapath support for headless service pods
  pkg/globalnet/controllers/global_ingressip_controller.go
  pkg/globalnet/controllers/global_ingressip_controller_test.go
  pkg/globalnet/controllers/iptables/iface.go
Labels: ready-to-test

#1462 Rename podWatcher to egressPodWatcher
  pkg/globalnet/controllers/egress_pod_watcher.go
  pkg/globalnet/controllers/global_egressip_controller.go
  pkg/globalnet/controllers/types.go
Labels: ready-to-test

#1457 Reconcile GlobalIngressIPs on startup
  pkg/globalnet/controllers/base_controllers.go
  pkg/globalnet/controllers/gateway_monitor.go
  pkg/globalnet/controllers/global_ingressip_controller.go
  pkg/globalnet/controllers/ingress_pod_controller.go
  pkg/globalnet/controllers/service_controller.go
  pkg/globalnet/controllers/service_controller_test.go
  pkg/globalnet/controllers/service_export_controller.go
  pkg/globalnet/controllers/service_export_controller_test.go
  pkg/globalnet/controllers/types.go
Labels: ready-to-test

#1454 Fix issues with MTU settings
  pkg/routeagent_driver/handlers/mtu/mtuhandler.go
  pkg/routeagent_driver/main.go
Labels: ready-to-test

#1468 Increase days until stale to 120
  .github/stale.yml
Labels: ready-to-test

#1470 Remove the old Globalnet 1.0 code
  pkg/globalnet/controllers/ipam/constants.go
  pkg/globalnet/controllers/ipam/gatewaymonitor.go
  pkg/globalnet/controllers/ipam/gatewaymonitor_test.go
  pkg/globalnet/controllers/ipam/globalnet.go
  pkg/globalnet/controllers/ipam/globalnet_egress.go
  pkg/globalnet/controllers/ipam/globalnet_ingress.go
  pkg/globalnet/controllers/ipam/ipam.go
  pkg/globalnet/controllers/ipam/ipam_suite_test.go
  pkg/globalnet/controllers/ipam/ippool.go
  pkg/globalnet/controllers/ipam/ippool_test.go
  pkg/globalnet/controllers/ipam/metrics.go
  pkg/globalnet/controllers/ipam/node_handler.go
  pkg/globalnet/controllers/ipam/pod_handler.go
  pkg/globalnet/controllers/ipam/service_export_handler.go
  pkg/globalnet/controllers/ipam/service_handler.go
  pkg/globalnet/controllers/ipam/types.go
Labels: ready-to-test

#1450 Miscellaneous upgrades
  go.mod
  go.sum
Labels: ready-to-test

#1467 Disable the deprecated interfacer linter
  .golangci.yml
Labels: ready-to-test

#1472 Elide starting egressPodWatcher on failure
  pkg/globalnet/controllers/global_egressip_controller.go
  pkg/globalnet/controllers/global_egressip_controller_test.go
Labels: ready-to-test

#1478 Use the K8s uuid package instead of Google's
  go.mod
  pkg/globalnet/controllers/controllers_suite_test.go
Labels: ready-to-test

#1458 Remove makefile special args
  .github/workflows/e2e-external.yml
  .github/workflows/e2e-full.yml
  Makefile
Labels: ready-to-test

#1464 Use SHAs for all GHA versions
  .github/workflows/codeowners.yml
  .github/workflows/dependent-issues.yml
  .github/workflows/e2e-full.yml
  .github/workflows/e2e.yml
  .github/workflows/flake_finder.yml
  .github/workflows/linting.yml
  .github/workflows/periodic.yml
  .github/workflows/release.yml
  .github/workflows/unit.yml
  .github/workflows/upgrade-e2e.yml
Labels: automation, ready-to-test

#1469 Drop iptables from the gateway image
  package/Dockerfile.submariner-gateway
Labels: ready-to-test

#1474 Move the iptables tools to the iptables package
  pkg/globalnet/controllers/gateway_monitor.go
  pkg/iptables/iptables.go
  pkg/routeagent_driver/handlers/kubeproxy/iptables_iface.go
  pkg/routeagent_driver/handlers/ovn/gateway_dataplane.go
  pkg/routeagent_driver/iptables/iptables.go
  pkg/util/util.go
Labels: ready-to-test

#1475 Remove prep_for_subm
  tools/openshift/ocp-ipi-aws/README.md
  tools/openshift/ocp-ipi-aws/main.tf
  tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/ec2-resources.tf
  tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/machine-set-resources.tf
  tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/outputs.tf
  tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/templates/machine-set.yaml
  tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/variables.tf
  tools/openshift/ocp-ipi-aws/ocp-ipi-aws-prep/vpc-resources.tf
  tools/openshift/ocp-ipi-aws/outputs.tf
  tools/openshift/ocp-ipi-aws/prep_for_subm.sh
  tools/openshift/ocp-ipi-aws/versions.tf
Labels: ready-to-test

#1485 Add UT for MTUHandler
  pkg/netlink/fake/netlink.go
  pkg/routeagent_driver/handlers/mtu/mtuhandler.go
  pkg/routeagent_driver/handlers/mtu/mtuhandler_suite_test.go
  pkg/routeagent_driver/handlers/mtu/mtuhandler_test.go
Labels: ready-to-test

#1482 E2E: Headless Services with globalnet
  go.mod
  go.sum
  test/e2e/dataplane/tcp_gn_pod_connectivity.go
  test/e2e/framework/dataplane.go
Labels: ready-to-test

#1497 Implement e2e tests for GlobalEgressIP use-cases
  go.mod
  go.sum
  test/e2e/dataplane/tcp_gn_pod_connectivity.go
  test/e2e/framework/dataplane.go
  test/e2e/framework/framework.go
  test/e2e/redundancy/gateway_failover.go
  test/e2e/redundancy/route_agent_restart.go
Labels: globalnet, ready-to-test

#1494 Use Conditions*Unstructured functions from admiral
  go.mod
  go.sum
  pkg/globalnet/controllers/base_controllers.go
  pkg/globalnet/controllers/global_egressip_controller.go
Labels: ready-to-test

#1493 Remove project-specific gitlint configuration
  .gitlint
Labels: ready-to-test

#1496 Update default number of cluster egress IPs
  pkg/globalnet/controllers/cluster_egressip_controller.go
  pkg/globalnet/controllers/cluster_egressip_controller_test.go
  pkg/globalnet/controllers/gateway_monitor_test.go
  pkg/globalnet/controllers/types.go
  test/e2e/dataplane/tcp_gn_pod_connectivity.go
  test/e2e/framework/dataplane.go
Labels: ready-to-test

#1499 Ignore CNI Interface when healthcheck is disabled
  pkg/endpoint/local_endpoint.go
  test/e2e/dataplane/gateway_status.go
Labels: ready-to-test

#1501 Revert MTU probe changes
  pkg/netlink/fake/netlink.go
  pkg/routeagent_driver/handlers/mtu/mtuhandler.go
  pkg/routeagent_driver/handlers/mtu/mtuhandler_suite_test.go
  pkg/routeagent_driver/handlers/mtu/mtuhandler_test.go
  pkg/routeagent_driver/main.go
Labels: ready-to-test

#1491 Error deleting IP table rule during node update event
  pkg/globalnet/controllers/node_controller.go
Labels: ready-to-test

#1483 Increase the waiting time for a LoadBalancer to be ready
  pkg/endpoint/public_ip.go
  pkg/endpoint/public_ip_test.go
Labels: 0.10.0-testday, ready-to-test

#1500 Add clamp rules to fix TCP MTU issue
  package/Dockerfile.submariner-route-agent
  pkg/routeagent_driver/constants/constants.go
  pkg/routeagent_driver/handlers/mtu/mtuhandler.go
  pkg/routeagent_driver/handlers/mtu/mtuhandler_suite_test.go
  pkg/routeagent_driver/handlers/mtu/mtuhandler_test.go
  pkg/routeagent_driver/main.go
Labels: 0.10.0-testday, ready-to-test

#1502 Do not collect duplicated information
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: ready-to-test

#1498 Use the CNI interface IP as src ip for g/w hostnetworking traffic
  pkg/cable/vxlan/vxlan.go
Labels: bug, ready-to-test, vxlan

#1504 fix udp port publishing
  pkg/apis/submariner.io/v1/types.go
  pkg/endpoint/local_endpoint.go
  pkg/endpoint/local_endpoint_test.go
Labels: backport, ready-to-test

#1505 Include procps-ng which is internally used by libreswan
  package/Dockerfile.submariner-gateway
  package/pluto
Labels: ready-to-test

#1507 Run Flake Finder every 2h for 0.10.0 testing
  .github/workflows/flake_finder.yml
Labels: automation, ready-to-test
