Repository submariner-io/submariner, pull requests merged in 2021-01, with the labels that each got.

#1075 Fix bug in findChassisByHostname matching
  pkg/networkplugin-syncer/handlers/ovn/router_submariner_south.go
Labels: OVN, backport, bug

#1066 Add a license header check
  .github/workflows/linting.yml
  .legal.json
  pkg/globalnet/controllers/ipam/node_handler.go
Labels: cncf

#1070 Expose prometheus metrics for globalnet
  pkg/globalnet/main.go
Labels: metrics

#1086 Use the PR base branch as reference when linting
  .github/workflows/linting.yml
Labels: backport

#1089 Fix SSL detection in OVN connection string
  pkg/networkplugin-syncer/handlers/ovn/connection.go
Labels: backport

#1092 Handle empty port name in kubeProxyClusterIpServiceChainName
  pkg/globalnet/controllers/ipam/globalnet.go
  pkg/globalnet/controllers/ipam/globalnet_ingress.go
Labels: backport, bug

#1090 Tag released image with branch name
  .github/workflows/release.yml
Labels: backport

#1107 Cleanup additional space and stop removing swap
  .github/workflows/e2e.yml
Labels: OVN, automation, backport

#965 Switch to Fedora for all images
  package/Dockerfile.submariner-globalnet
  package/Dockerfile.submariner-route-agent
Labels: multiarch
