Repository submariner-io/submariner, pull requests merged in 2021-08, with the labels that each got.

#1511 Limit cluster-id to 63 chars
  pkg/apis/submariner.io/v1/types.go
Labels: ready-to-test

#1513 E2e, delete ServiceExport before Service
  test/e2e/framework/dataplane.go
Labels: globalnet, ready-to-test

#1516 Fix typo in the log message
  pkg/globalnet/controllers/global_egressip_controller.go
Labels: ready-to-test

#1521 Don't run periodic PR dependency checks on forks
  .github/workflows/dependent-issues.yml
Labels: automation, ready-to-test

#1525 Run Flake Finder twice a day
  .github/workflows/flake_finder.yml
Labels: automation, ready-to-test

#1520 Fix e2e failure when health-check is disabled
  test/e2e/dataplane/gateway_status.go
Labels: ready-to-test

#1534 Split out an API module
  .lichen.yaml
  Makefile
  go.mod
  pkg/apis/LICENSE
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: ready-to-test

#1536 Add the proper version for pkg/apis
  go.mod
Labels: ready-to-test

#1532 Upgrade to Fedora 34
  package/Dockerfile.submariner-gateway
  package/Dockerfile.submariner-globalnet
  package/Dockerfile.submariner-networkplugin-syncer
  package/Dockerfile.submariner-route-agent
Labels: dependencies, technical-debt, ready-to-test

#1539 Fix YAML linting errors
  .github/dependabot.yml
  .github/workflows/dependent-issues.yml
  .golangci.yml
  .lichen.yaml
  .submarinerbot.yaml
Labels: bug, automation, ready-to-test

#1541 Remove non-functional yamllint strict config
  .yamllint.yml
Labels: automation, ready-to-test

#1542 Update create-issue-from-file GHA 2.3.2 to 3.0.0
  .github/workflows/periodic.yml
Labels: dependencies, automation, ready-to-test

#1543 Revert to a r/w version of dependent-issues
  .github/workflows/dependent-issues.yml
Labels: ready-to-test
