Repository submariner-io/submariner, pull requests merged in 2022-02, with the labels that each got.

#1647 Add a new metric for telemetry usage
  pkg/cable/metrics.go
Labels: metrics, ready-to-test

#1692 Remove sourcing cluster_settings since it has been deleted
  scripts/reload-images
Labels: ready-to-test

#1691 Clean up Endpoints and Clusters on uninstall
  main.go
  pkg/controllers/datastoresyncer/datastore_cluster_sync_test.go
  pkg/controllers/datastoresyncer/datastore_endpoint_sync_test.go
  pkg/controllers/datastoresyncer/datastoresyncer.go
  pkg/controllers/datastoresyncer/datastoresyncer_suite_test.go
Labels: ready-to-test

#1686 Don't skip external net test in external net E2E
  .github/workflows/e2e-full.yml
Labels: automation, ready-to-test

#1701 Adjust to Shipyard framework changes
  go.mod
  go.sum
  test/e2e/framework/dataplane.go
Labels: ready-to-test

#1704 Fix gateway failure on uninstall
  main.go
Labels: ready-to-test

#1702 Don't recommend deploying operator directly
  README.md
Labels: docs, ready-to-test

#1705 Use `reload-images` from Shipyard
  Makefile
  scripts/reload-images
Labels: ready-to-test

#1706 Routeagent datapath cleanup
  pkg/routeagent_driver/constants/constants.go
  pkg/routeagent_driver/handlers/kubeproxy/iptables_iface.go
  pkg/routeagent_driver/handlers/kubeproxy/uninstall.go
Labels: ready-to-test

#1708 Fix new linter errors from golangci-lint 1.44.2
  pkg/cable/driver.go
  pkg/cableengine/healthchecker/healthchecker.go
  pkg/ipset/ipset.go
  pkg/netlink/netlink.go
  pkg/routeagent_driver/handlers/ovn/handler.go
Labels: automation, ready-to-test

#1709 Some clusters are missing routes
  pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go
Labels: ready-to-test
