Repository submariner-io/submariner, pull requests merged in 2022-05, with the labels that each got.

#1676 Build images without Dapper
  Makefile
  package/Dockerfile.submariner-gateway
  package/Dockerfile.submariner-globalnet
  package/Dockerfile.submariner-networkplugin-syncer
  package/Dockerfile.submariner-route-agent
Labels: ready-to-test, epic:multi-arch, next-version-candidate

#1806 Adjust to NewUpdateFederator API changes in globalnet
  go.mod
  go.sum
  pkg/globalnet/controllers/cluster_egressip_controller.go
  pkg/globalnet/controllers/global_egressip_controller.go
  pkg/globalnet/controllers/global_ingressip_controller.go
  pkg/globalnet/controllers/node_controller.go
  pkg/globalnet/controllers/service_controller.go
Labels: ready-to-test

#1816 Bump markdown-link-check to the current tip
  .github/workflows/linting.yml
  .github/workflows/periodic.yml
Labels: ready-to-test

#1805 Verify local cidr ipset is updated with local PodCIDRs
  pkg/routeagent_driver/handlers/mtu/mtuhandler.go
  pkg/routeagent_driver/handlers/mtu/mtuhandler_test.go
  pkg/routeagent_driver/main.go
Labels: ready-to-test

#1821 [Backport] Verify local cidr ipset is updated with local PodCIDRs
  pkg/routeagent_driver/handlers/mtu/mtuhandler.go
  pkg/routeagent_driver/handlers/mtu/mtuhandler_test.go
  pkg/routeagent_driver/main.go
Labels: ready-to-test, automated-backport

#1827 Document TODOs
  pkg/iptables/fake/iptables.go
Labels: ready-to-test, maintenance

#1831 Require Go 1.17
  go.mod
  go.sum
Labels: ready-to-test

#1817 Use Dependabot to update GHAs on release-0.12
  .github/dependabot.yml
Labels: ready-to-test, maintenance

#1838 Automated backport of #1816: Bump markdown-link-check to the current tip
  .github/workflows/linting.yml
  .github/workflows/periodic.yml
Labels: automated-backport

#1830 Update mtuhandler to support platform running nftables
  pkg/routeagent_driver/environment/env.go
  pkg/routeagent_driver/handlers/mtu/mtuhandler.go
  pkg/routeagent_driver/handlers/mtu/mtuhandler_test.go
  pkg/routeagent_driver/main.go
Labels: bug, backport, ready-to-test

#1843 Configure timeout while resolving public-ip
  pkg/endpoint/public_ip.go
Labels: ready-to-test

#1846 Update mtuhandler to support platform running nftables
  pkg/routeagent_driver/environment/env.go
  pkg/routeagent_driver/handlers/mtu/mtuhandler.go
  pkg/routeagent_driver/handlers/mtu/mtuhandler_test.go
  pkg/routeagent_driver/main.go
Labels: ready-to-test, automated-backport

#1851 Fix connection failure with LB mode + VxLAN Cabledriver
  pkg/util/util.go
Labels: ready-to-test
