Repository submariner-io/submariner, pull requests merged in 2022-11, with the labels that each got.

#2094 Automated backport of #2086: Log error message for fdb errors
  pkg/cable/vxlan/vxlan.go
Labels: automated-backport

#2093 Automated backport of #2086: Log error message for fdb errors
  pkg/cable/vxlan/vxlan.go
Labels: automated-backport

#2017 Refactor GatewayPodRestart test
  test/e2e/redundancy/gateway_failover.go
Labels: ready-to-test

#2100 Use golangci-lint for header checks
  .github/workflows/linting.yml
  .golangci.yml
  .licenserc.json
  pkg/globalnet/controllers/ingress_endpoints_controller.go
  pkg/globalnet/controllers/ingress_endpoints_controllers.go
Labels: ready-to-test

#2103 remove io/util for advanced golang
  pkg/util/clusterfiles/cluster_files.go
Labels: ready-to-test

#2099 Add release notes for #2087
  release-notes/20221103-mss-clamp.md
Labels: ready-to-test

#2116 Avoid using api.ipify.org as the first resolver for public-ip
  pkg/endpoint/public_ip.go
Labels: ready-to-test

#2117 [Backport] Avoid using api.ipify.org as the first resolver for public-ip (#2116)
  pkg/endpoint/public_ip.go
Labels: ready-to-test, automated-backport

#2118 [Backport] Avoid using api.ipify.org as the first resolver for public-ip (#2116)
  pkg/endpoint/public_ip.go
Labels: automated-backport

#2120 Fix wrong log message
  main.go
Labels: ready-to-test

#2133 Revert "Remove TCP MSS clamping rules from filter table (#2016)"
  pkg/routeagent_driver/handlers/ovn/gateway_dataplane.go
Labels: ready-to-test

#2134 [Backport] Revert "Remove TCP MSS clamping rules from filter table (#2016)"
  pkg/routeagent_driver/handlers/ovn/gateway_dataplane.go
Labels: ready-to-test

#2129 Configure dependabot for 0.14
  .github/dependabot.yml
Labels: ready-to-test

#2147 More gofumpt with Go 1.19
  pkg/routeagent_driver/handlers/ovn/gateway_dataplane.go
Labels: ready-to-test

#2156 Update generated code using Go 1.19
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/natdiscovery/proto/natdiscovery.pb.go
Labels: ready-to-test

#2144 Switch from go-ping to pro-bing
  go.mod
  go.sum
  pkg/cableengine/healthchecker/pinger.go
  pkg/cableengine/healthchecker/pinger_test.go
Labels: dependencies, ready-to-test

#2158 Ignore go.sum changes when linting
  .github/workflows/linting.yml
Labels: automation, backport, ready-to-test

#2160 Automated backport of #2158: Ignore go.sum changes when linting
  .github/workflows/linting.yml
Labels: ready-to-test, automated-backport

#2161 Automated backport of #2158: Ignore go.sum changes when linting
  .github/workflows/linting.yml
Labels: ready-to-test, automated-backport

#2159 Automated backport of #2158: Ignore go.sum changes when linting
  .github/workflows/linting.yml
Labels: ready-to-test, automated-backport
