Repository submariner-io/submariner, pull requests merged in 2022-07, with the labels that each got.

#1903 Restart health check pinger in case it failed
  pkg/cableengine/healthchecker/pinger.go
Labels: ready-to-test

#1897 Uninstall support for ovn
  pkg/networkplugin-syncer/handlers/ovn/uninstall.go
  pkg/routeagent_driver/handlers/ovn/uninstall.go
  pkg/routeagent_driver/handlers/ovn/vsctl/vsctl.go
Labels: backport, ready-to-test

#1913 Automated backport of #1911: Limit the number of open files in dnf_install
  package/dnf_install
Labels: ready-to-test, automated-backport

#1908 Restart health check pinger in case it failed
  pkg/cableengine/healthchecker/pinger.go
Labels: ready-to-test

#1910 Automated backport of #1897: Uninstall support for ovn
  pkg/networkplugin-syncer/handlers/ovn/uninstall.go
  pkg/routeagent_driver/handlers/ovn/uninstall.go
  pkg/routeagent_driver/handlers/ovn/vsctl/vsctl.go
Labels: ready-to-test, automated-backport

#1916 Constantly update passive GW object timestamp
  pkg/cableengine/syncer/syncer.go
Labels: backport, ready-to-test

#1923 Refactor syncer Gateway update
  pkg/cableengine/syncer/syncer.go
  pkg/cableengine/syncer/syncer_test.go
Labels: ready-to-test

#1931 Automated backport of #1919: Bump x/text to address CVE-2021-38561
  go.mod
  go.sum
Labels: ready-to-test, automated-backport

#1934 Remove cni interface annotation as part of uninstall command (#1729)
  pkg/routeagent_driver/cni/cni_iface.go
Labels: ready-to-test

#1935 Run the upgrade job on devel only
  .github/workflows/upgrade-e2e.yml
Labels: backport, ready-to-test, maintenance

#1937 Bump protobuf to 1.28.0
  go.mod
  go.sum
  pkg/natdiscovery/proto/natdiscovery.pb.go
Labels: ready-to-test

#1938 Automated backport of #1935: Run the upgrade job on devel only
  .github/workflows/upgrade-e2e.yml
Labels: ready-to-test, automated-backport

#1939 Automated backport of #1935: Run the upgrade job on devel only
  .github/workflows/upgrade-e2e.yml
Labels: ready-to-test, automated-backport

#1925 Bump K8s to 0.24.2
  go.mod
  go.sum
  main.go
Labels: ready-to-test

#1941 Add constant for Flannel CNI
  pkg/cni/plugins.go
  pkg/routeagent_driver/handlers/kubeproxy/kp_iptables.go
Labels: ready-to-test
