Repository submariner-io/submariner, pull requests merged in 2022-08, with the labels that each got.

#1942 Use ENV vars instead of flags
  Makefile
  pkg/cable/wireguard/README.md
  scripts/e2e/external/utils
Labels: ready-to-test

#1948 Set ReadHeaderTimeout to 60s to mitigate Slowloris
  main.go
  pkg/globalnet/main.go
Labels: bug, ready-to-test

#1951 Fix API name and some minor corrections in text
  pkg/networkplugin-syncer/handlers/ovn/handler.go
  pkg/networkplugin-syncer/handlers/ovn/ovn_submariner_infrastructure.go
  pkg/routeagent_driver/handlers/ovn/host_networking.go
  pkg/routeagent_driver/handlers/ovn/south_rules.go
Labels: ready-to-test

#1952 Use OVSDBTimeout const while creating the client
  pkg/networkplugin-syncer/handlers/ovn/connection.go
  pkg/networkplugin-syncer/handlers/ovn/const.go
Labels: ready-to-test

#1950 Cleanup the host routes programmed by OVN RA plugin
  pkg/routeagent_driver/handlers/ovn/uninstall.go
Labels: backport, ready-to-test

#1953 [Backport] Cleanup the host routes programmed by OVN RA plugin
  pkg/routeagent_driver/handlers/ovn/uninstall.go
Labels: ready-to-test

#1954 Make sure redundancy E2E skips inadequate clusters
  test/e2e/redundancy/gateway_failover.go
  test/e2e/redundancy/route_agent_restart.go
Labels: ready-to-test

#1956 Require Go 1.18
  go.mod
Labels: dependencies, ready-to-test, maintenance

#1967 Use env vars for metrics ports
  main.go
  pkg/globalnet/controllers/types.go
  pkg/globalnet/main.go
  pkg/types/types.go
Labels: ready-to-test

#1961 Add Anchore vulnerability scanning on PRs
  .github/workflows/linting.yml
  .grype.yaml
Labels: ready-to-test, maintenance

#1968 Run Anchore scan on merges to devel/release-*
  .github/workflows/report.yml
Labels: ready-to-test

#1969 Wrapped error is always nil
  pkg/networkplugin-syncer/handlers/ovn/ovn_submariner_infrastructure.go
Labels: ready-to-test

#1980 Minimize GHA permissions
  .github/workflows/branch.yml
  .github/workflows/codeowners.yml
  .github/workflows/dependent-issues.yml
  .github/workflows/e2e-full.yml
  .github/workflows/e2e.yml
  .github/workflows/flake_finder.yml
  .github/workflows/linting.yml
  .github/workflows/multiarch.yml
  .github/workflows/periodic.yml
  .github/workflows/release.yml
  .github/workflows/report.yml
  .github/workflows/twitter-together.yml
  .github/workflows/unit.yml
  .github/workflows/upgrade-e2e.yml
Labels: ready-to-test

#1988 Check GHA updates weekly
  .github/dependabot.yml
Labels: ready-to-test
