Repository submariner-io/submariner, pull requests merged in 2022-12, with the labels that each got.

#2172 Bump to Go 1.19
  go.mod
  go.sum
Labels: ready-to-test

#2163 Run dependabot for go weekly, all updates at once
  .github/dependabot.yml
Labels: automation, ready-to-test

#2164 Fix issues with gateway public-ip resolver
  pkg/endpoint/local_endpoint.go
  pkg/endpoint/public_ip.go
  pkg/endpoint/public_ip_watcher.go
Labels: backport, backport-handled, ready-to-test

#2177 Enable 2 gateways for E2E fail-over test
  .shipyard.e2e.yml
  go.mod
  go.sum
Labels: ready-to-test

#2183 Automated backport of #2164: Fix issues with gateway public-ip resolver
  pkg/endpoint/local_endpoint.go
  pkg/endpoint/public_ip.go
  pkg/endpoint/public_ip_watcher.go
Labels: ready-to-test, automated-backport

#2182 Automated backport of #2017: Refactor GatewayPodRestart test
  test/e2e/redundancy/gateway_failover.go
Labels: ready-to-test, automated-backport

#2185 Automated backport of #2177: Enable 2 gateways for E2E fail-over test
  .shipyard.e2e.yml
  go.mod
  go.sum
Labels: ready-to-test, automated-backport

#2196 Bump to Kubernetes 0.26 dependencies
  go.mod
  go.sum
  pkg/cableengine/syncer/syncer_test.go
  test/e2e/framework/framework.go
Labels: ready-to-test

#2206 [Backport] Public-ip resolver, change err log to debug (#2201)
  pkg/endpoint/public_ip.go
  pkg/endpoint/public_ip_internal_test.go
Labels: ready-to-test, automated-backport

#2217 Align with K8s 1.26
  go.mod
  go.sum
  test/e2e/cluster/add_remove_cluster.go
  test/e2e/framework/dataplane.go
  test/e2e/redundancy/gateway_failover.go
  test/external/dataplane/connectivity.go
  test/external/dataplane/gn_connectivity.go
Labels: ready-to-test

#2218 Skip one of the e2e ext-net tests
  test/external/dataplane/connectivity.go
Labels: ready-to-test

#2216 Simplify E2E and Flake Finder GHAs
  .github/workflows/e2e-full.yml
  .github/workflows/flake_finder.yml
  Makefile
Labels: ready-to-test, maintenance

#2224 Bump the WireGuard dependency
  go.mod
  go.sum
Labels: ready-to-test
