Repository submariner-io/submariner, pull requests merged in 2022-03, with the labels that each got.

#1721 Delete iptable rules when remote ep is deleted
  pkg/routeagent_driver/handlers/kubeproxy/iptables_iface.go
Labels: backport, ready-to-test

#1723 Backport: Delete iptable rules when remote ep is deleted
  pkg/routeagent_driver/handlers/kubeproxy/iptables_iface.go
Labels: ready-to-test

#1722 Remove MTU flows as part of uninstall command
  pkg/routeagent_driver/handlers/kubeproxy/uninstall.go
  pkg/routeagent_driver/handlers/mtu/mtuhandler.go
Labels: backport, ready-to-test

#1714 Bump actions/checkout to v3
  .github/workflows/codeowners.yml
  .github/workflows/e2e-full.yml
  .github/workflows/e2e.yml
  .github/workflows/flake_finder.yml
  .github/workflows/linting.yml
  .github/workflows/periodic.yml
  .github/workflows/release.yml
  .github/workflows/twitter-together.yml
  .github/workflows/unit.yml
  .github/workflows/upgrade-e2e.yml
Labels: ready-to-test

#1730 Bump E2E-full K8s version 1.20->1.23
  .github/workflows/e2e-full.yml
Labels: automation, ready-to-test

#1729 Remove cni interface annotation as part of uninstall command
  pkg/routeagent_driver/cni/cni_iface.go
  pkg/routeagent_driver/main.go
Labels: ready-to-test

#1737 Only ignore Dockerfile.* in the root directory
  .gitignore
Labels: ready-to-test

#1754 Fix log message in route-agent handler
  pkg/routeagent_driver/main.go
Labels: ready-to-test

#1733 Update actions/upload-artifact from 2.2.4 to 3.0.0
  .github/workflows/unit.yml
Labels: ready-to-test, maintenance

#1751 Use Dependabot to update GHAs, now supports SHAs
  .github/dependabot.yml
Labels: ready-to-test, maintenance

#1582 Add more E2E tests for external connectivity use case
  test/external/dataplane/connectivity.go
  test/external/dataplane/gn_connectivity.go
Labels: ready-to-test

#1756 Improve logs in Globalnet controller
  pkg/globalnet/controllers/global_ingressip_controller.go
  pkg/globalnet/controllers/service_export_controller.go
Labels: ready-to-test

#1764 Create GN-Mark chain before starting EP watcher
  pkg/globalnet/controllers/gateway_monitor.go
Labels: ready-to-test

#1743 Set up the multi-active-gw branch
  .github/workflows/branch.yml
  .github/workflows/e2e-full.yml
  .github/workflows/e2e.yml
  .github/workflows/flake_finder.yml
  .github/workflows/release.yml
  .github/workflows/twitter-together.yml
  .github/workflows/upgrade-e2e.yml
  CODEOWNERS
  CODEOWNERS.in
  Makefile
  test/e2e/framework/dataplane.go
  tweets/README.md
  tweets/hello-world.tweet
Labels: ready-to-test
