Repository submariner-io/submariner, pull requests merged in 2022-10, with the labels that each got.

#2029 Use the default kind CNI
  .shipyard.e2e.yml
Labels: ready-to-test

#2042 Add issues:write permission to broken links GHA
  .github/workflows/periodic.yml
Labels: automation, ready-to-test

#2047 Use zerolog in the network plugin syncer
  pkg/networkplugin-syncer/handlers/ovn/connection.go
  pkg/networkplugin-syncer/handlers/ovn/handler.go
  pkg/networkplugin-syncer/handlers/ovn/ovn_submariner_infrastructure.go
  pkg/networkplugin-syncer/handlers/ovn/uninstall.go
  pkg/networkplugin-syncer/main.go
Labels: ready-to-test

#2046 Use zerolog in globalnet
  pkg/globalnet/controllers/base_controllers.go
  pkg/globalnet/controllers/cluster_egressip_controller.go
  pkg/globalnet/controllers/controllers_suite_test.go
  pkg/globalnet/controllers/egress_pod_watcher.go
  pkg/globalnet/controllers/endpoints_controller.go
  pkg/globalnet/controllers/gateway_monitor.go
  pkg/globalnet/controllers/global_egressip_controller.go
  pkg/globalnet/controllers/global_ingressip_controller.go
  pkg/globalnet/controllers/ingress_endpoints_controller.go
  pkg/globalnet/controllers/ingress_endpoints_controllers.go
  pkg/globalnet/controllers/ingress_pod_controller.go
  pkg/globalnet/controllers/ingress_pod_controllers.go
  pkg/globalnet/controllers/iptables/iface.go
  pkg/globalnet/controllers/node_controller.go
  pkg/globalnet/controllers/service_controller.go
  pkg/globalnet/controllers/service_export_controller.go
  pkg/globalnet/controllers/service_export_endpoints_controllers.go
  pkg/globalnet/controllers/types.go
  pkg/globalnet/controllers/uninstall.go
  pkg/globalnet/main.go
Labels: ready-to-test

#2045 Add Sonar unit test coverage reporting
  .github/workflows/report.yml
  sonar-project.properties
Labels: automation, ready-to-test

#2053 Skip public-ip resolution in air-gapped clusters
  main.go
  pkg/endpoint/local_endpoint.go
  pkg/endpoint/local_endpoint_test.go
  pkg/endpoint/public_ip.go
  pkg/endpoint/public_ip_internal_test.go
  pkg/endpoint/public_ip_watcher.go
Labels: ready-to-test

#2056 Automated backport of #2029: Use the default kind CNI
  .shipyard.e2e.yml
Labels: ready-to-test, automated-backport

#2055 Automated backport of #2029: Use the default kind CNI
  .shipyard.e2e.yml
Labels: ready-to-test, automated-backport

#2040 Export the supported network plugins
  pkg/cni/plugins.go
  pkg/routeagent_driver/handlers/kubeproxy/kp_iptables.go
Labels: ready-to-test

#2065 Sonar shallow clone, remove debug
  .github/workflows/report.yml
Labels: automation, ready-to-test

#2062 Add fake dir as Sonar test code, ignore client dir
  sonar-project.properties
Labels: automation, ready-to-test

#2060 Refactor main to reduce cognitive complexity
  main.go
Labels: ready-to-test

#2064 Fix broken twitter-together link
  tweets/README.md
Labels: automation, ready-to-test

#2073 Remove space between // and nolint
  pkg/cable/libreswan/libreswan.go
  pkg/cable/wireguard/driver.go
  pkg/cableengine/cableengine.go
  pkg/cableengine/fake/cableengine.go
  pkg/cableengine/syncer/syncer.go
  pkg/controllers/datastoresyncer/datastoresyncer.go
  pkg/endpoint/public_ip.go
  pkg/endpoint/public_ip_watcher.go
  pkg/event/controller/endpoint_created.go
  pkg/event/controller/endpoint_removed.go
  pkg/event/controller/endpoint_updated.go
  pkg/event/registry.go
  pkg/globalnet/controllers/base_controllers.go
  pkg/globalnet/controllers/cluster_egressip_controller.go
  pkg/globalnet/controllers/gateway_monitor.go
  pkg/globalnet/controllers/global_egressip_controller.go
  pkg/globalnet/controllers/global_ingressip_controller.go
  pkg/globalnet/controllers/iptables/iface.go
  pkg/globalnet/controllers/uninstall.go
  pkg/ipset/named.go
  pkg/natdiscovery/natdiscovery.go
  pkg/netlink/adapter.go
  pkg/netlink/fake/netlink.go
  pkg/netlink/netlink.go
  pkg/routeagent_driver/cabledriver/vxlan_tunnel_cleanup_handler.go
  pkg/routeagent_driver/cabledriver/xfrm_cleanup_handler.go
  pkg/routeagent_driver/cni/cni_iface.go
  test/e2e/dataplane/gateway_status.go
Labels: ready-to-test

#2072 Fix race condition in ovn routeagent handler
  pkg/routeagent_driver/handlers/ovn/handler.go
Labels: ready-to-test

#2084 Update the Shipyard test framework
  go.mod
  go.sum
  test/e2e/cluster/add_remove_cluster.go
  test/e2e/redundancy/gateway_failover.go
  test/e2e/redundancy/route_agent_restart.go
Labels: ready-to-test

#2086 Log error message for fdb errors
  pkg/cable/vxlan/vxlan.go
Labels: ready-to-test

#2087 Allow setting TCP MSS clamping value also for non GN
  pkg/routeagent_driver/handlers/mtu/mtuhandler.go
Labels: backport, ready-to-test

#2091 [Backport] Allow setting TCP MSS clamping value also for non GN (#2087)
  pkg/routeagent_driver/handlers/mtu/mtuhandler.go
Labels: ready-to-test, automated-backport

#2092 [Backport] Allow setting TCP MSS clamping value also for non GN (#2087)
  pkg/routeagent_driver/handlers/mtu/mtuhandler.go
Labels: ready-to-test, automated-backport

#2014 Refactor GatewayFailOver test
  test/e2e/redundancy/gateway_failover.go
Labels: ready-to-test
