Repository submariner-io/submariner, pull requests merged in 2022-06, with the labels that each got.

#1863 Update K8s dependabot config
  .github/dependabot.yml
Labels: ready-to-test

#1859 Refactor constants used externally
  pkg/apis/submariner.io/v1/types.go
  pkg/cni/plugins.go
  pkg/endpoint/local_endpoint.go
  pkg/event/registry_test.go
  pkg/networkplugin-syncer/handlers/ovn/handler.go
  pkg/networkplugin-syncer/main.go
  pkg/port/ports.go
  pkg/routeagent_driver/constants/constants.go
  pkg/routeagent_driver/handlers/kubeproxy/constants.go
  pkg/routeagent_driver/handlers/kubeproxy/iptables_iface.go
  pkg/routeagent_driver/handlers/kubeproxy/kp_iptables.go
  pkg/routeagent_driver/handlers/kubeproxy/uninstall.go
  pkg/routeagent_driver/handlers/kubeproxy/vxlan.go
  pkg/routeagent_driver/handlers/kubeproxy/vxlan_internal_test.go
  pkg/routeagent_driver/handlers/ovn/handler.go
  pkg/routeagent_driver/main.go
Labels: ready-to-test

#1865 remove redundant parentheses
  pkg/routeagent_driver/main.go
Labels: ready-to-test

#1870 Use NettestImageURL var from shipyard
  go.mod
  go.sum
  test/e2e/framework/dataplane.go
Labels: ready-to-test

#1872 Support override MTU value used in TCP MSS clamping
  pkg/apis/submariner.io/v1/types.go
  pkg/routeagent_driver/handlers/mtu/mtuhandler.go
  pkg/routeagent_driver/handlers/mtu/mtuhandler_test.go
  pkg/routeagent_driver/main.go
Labels: ready-to-test

#1882 Initialize libovsdb clients to any DB
  pkg/networkplugin-syncer/handlers/ovn/connection.go
Labels: ready-to-test

#1884 Automated backport of #1882: Initialize libovsdb clients to any DB
  pkg/networkplugin-syncer/handlers/ovn/connection.go
Labels: ready-to-test, automated-backport

#1888 Automated backport of #1885: Add grep to Globalnet and RouteAgent images
  package/Dockerfile.submariner-globalnet
  package/Dockerfile.submariner-route-agent
Labels: ready-to-test, automated-backport

#1891 Log missing cniInterfaceIP on node
  pkg/globalnet/controllers/node_controller.go
  pkg/routeagent_driver/handlers/kubeproxy/kp_iptables.go
Labels: backport, ready-to-test

#1895 Automated backport of #1885: Add grep to Globalnet and RouteAgent images
  package/Dockerfile.submariner-globalnet
  package/Dockerfile.submariner-route-agent
Labels: ready-to-test, automated-backport

#1898 [Backport] Log missing cniInterfaceIP on node
  pkg/globalnet/controllers/node_controller.go
  pkg/routeagent_driver/handlers/kubeproxy/kp_iptables.go
Labels: ready-to-test
