Repository submariner-io/submariner, pull requests merged in 2022-01, with the labels that each got.

#1648 Ignore tweets/README.md in markdownlint
  .markdownlintignore
Labels: ready-to-test

#1638 Use the PSK secret if possible
  pkg/cable/libreswan/libreswan.go
Labels: ready-to-test

#1646 Fix typo in the argument name
  pkg/globalnet/controllers/controllers_suite_test.go
Labels: ready-to-test

#1633 Tweet "Hello, world" about new Twitter automation
  tweets/hello-world.tweet
Labels: ready-to-test

#1630 Edit Submariner's README
  README.md
Labels: docs, ready-to-test

#1571 Ignore endpoint events if processed already.
  pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go
  pkg/routeagent_driver/handlers/kubeproxy/kp_iptables.go
Labels: backport, ready-to-test

#1661 Wait for whack to reap its process
  pkg/cable/libreswan/libreswan.go
Labels: ready-to-test

#1662 Move test for oldest K8s version to Operator
  .github/workflows/e2e-full.yml
Labels: automation, ready-to-test

#1665 Endpoint objects are updated with no change every 30s filling logs
  pkg/cableengine/cableengine.go
  pkg/controllers/tunnel/tunnel.go
Labels: ready-to-test

#1664 Add UNINSTALL env var to the controller processes
  main.go
  pkg/event/controller/controller.go
  pkg/globalnet/controllers/types.go
  pkg/globalnet/main.go
  pkg/networkplugin-syncer/main.go
  pkg/routeagent_driver/environment/env.go
  pkg/routeagent_driver/main.go
  pkg/types/types.go
Labels: ready-to-test

#1643 Enhance GN to support SVCs without KP dependency
  pkg/globalnet/controllers/base_controllers.go
  pkg/globalnet/controllers/controllers_suite_test.go
  pkg/globalnet/controllers/global_ingressip_controller.go
  pkg/globalnet/controllers/global_ingressip_controller_test.go
  pkg/globalnet/controllers/iptables/iface.go
  pkg/globalnet/controllers/service_export_controller.go
  pkg/globalnet/controllers/types.go
Labels: ready-to-test

#1673 Check for fixup commits in PRs
  .github/workflows/linting.yml
Labels: ready-to-test

#1671 Fix Twitter, Together! README link
  tweets/README.md
Labels: docs, automation, ready-to-test
