Repository submariner-io/submariner, pull requests merged in 2023-05, with the labels that each got.

#2421 Add E2E with IPv4/6 dual-stack job
  .github/workflows/e2e.yml
Labels: automation, ready-to-test

#2475 Automated backport of #2433: Fix vxlan cable driver issue on RHEL-9 Gateway nodes
  pkg/cable/vxlan/vxlan.go
  pkg/netlink/fake/netlink.go
  pkg/netlink/netlink.go
  pkg/routeagent_driver/handlers/kubeproxy/vxlan.go
Labels: ready-to-test, automated-backport

#2480 Release note for #667
  release-notes/20230508-ovn-gw-node.md
Labels: ready-to-test

#2486 Use case-insensitive comparision when checking the CNI name
  pkg/event/registry.go
Labels: ready-to-test

#2499 Avoid cableEngine cleanup when the gateway pod is restarted
  main.go
Labels: ready-to-test

#2342 Use the new sets.Clear() function
  pkg/ipset/fake/ipset.go
  pkg/routeagent_driver/handlers/kubeproxy/routes_iface.go
Labels: ready-to-test
