Repository submariner-io/submariner, pull requests merged in 2023-06, with the labels that each got.

#2504 Automated backport of #2499: Avoid cableEngine cleanup when the gateway pod is restarted
  main.go
Labels: ready-to-test, automated-backport

#2518 Automated backport of #2499: Avoid cableEngine cleanup when the gateway pod is restarted
  main.go
Labels: ready-to-test, automated-backport

#2517 Fix pluto crash when remote endpoint is unstable
  pkg/cable/libreswan/libreswan.go
Labels: ready-to-test

#2519 Automated backport of #2499: Avoid cableEngine cleanup when the gateway pod is restarted
  main.go
Labels: ready-to-test, automated-backport

#2521 Automated backport of #2517: Fix pluto crash when remote endpoint is unstable
  pkg/cable/libreswan/libreswan.go
Labels: automated-backport

#2520 Automated backport of #2517: Fix pluto crash when remote endpoint is unstable
  pkg/cable/libreswan/libreswan.go
Labels: ready-to-test, automated-backport

#2522 Automated backport of #2517: Fix pluto crash when remote endpoint is unstable
  pkg/cable/libreswan/libreswan.go
Labels: ready-to-test, automated-backport

#2523 Use EnsureNoResource in globalnet tests
  go.mod
  go.sum
  pkg/globalnet/controllers/controllers_suite_test.go
  pkg/globalnet/controllers/gateway_monitor_test.go
  pkg/globalnet/controllers/service_export_controller_test.go
Labels: ready-to-test

#2464 Add new API for adding router in OVN
  pkg/apis/submariner.io/v1/types.go
  pkg/apis/submariner.io/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/fake/fake_gatewayroute.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/fake/fake_nongatewayroute.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/fake/fake_submariner.io_client.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/gatewayroute.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/nongatewayroute.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/submariner.io_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/submariner.io/v1/gatewayroute.go
  pkg/client/informers/externalversions/submariner.io/v1/interface.go
  pkg/client/informers/externalversions/submariner.io/v1/nongatewayroute.go
  pkg/client/listers/submariner.io/v1/expansion_generated.go
  pkg/client/listers/submariner.io/v1/gatewayroute.go
  pkg/client/listers/submariner.io/v1/nongatewayroute.go
Labels: ready-to-test

#2526 Retry reading local node details from k8s-api
  pkg/node/node.go
Labels: backport, ready-to-test

#2532 Fix race in GN pod for out-of-order RemoteEndpoint events
  pkg/globalnet/controllers/gateway_monitor.go
  pkg/globalnet/controllers/types.go
Labels: backport, ready-to-test

#2537 Automated backport of #2532: Fix race in GN pod for out-of-order RemoteEndpoint events
  pkg/globalnet/controllers/gateway_monitor.go
  pkg/globalnet/controllers/types.go
Labels: ready-to-test, automated-backport

#2536 Automated backport of #2532: Fix race in GN pod for out-of-order RemoteEndpoint events
  pkg/globalnet/controllers/gateway_monitor.go
  pkg/globalnet/controllers/types.go
Labels: ready-to-test, automated-backport

#2547 Disable depguard
  .golangci.yml
Labels: ready-to-test

#2550 Pass functions to Eventually
  pkg/cableengine/healthchecker/healthchecker_test.go
Labels: ready-to-test

#2551 Add a few missing Expect() assertions
  pkg/globalnet/controllers/cluster_egressip_controller_test.go
  pkg/natdiscovery/natdiscovery_internal_test.go
Labels: ready-to-test

#2515 Add config syncer to reprogram routes in case of an accidental delete
  pkg/routeagent_driver/handlers/ovn/handler.go
  pkg/routeagent_driver/handlers/ovn/route_config_syncer.go
  pkg/routeagent_driver/handlers/ovn/uninstall.go
Labels: backport, priority:high, ready-to-test

#2560 Automated backport of #2515: Add config syncer to reprogram routes
  pkg/routeagent_driver/handlers/ovn/handler.go
  pkg/routeagent_driver/handlers/ovn/route_config_syncer.go
  pkg/routeagent_driver/handlers/ovn/uninstall.go
Labels: ready-to-test, automated-backport

#2568 Automated backport of #2486: Use case-insensitive comparision when checking the CNI name
  pkg/event/registry.go
Labels: automated-backport

#2566 Automated backport of #2542: Provide detailed logs for certificate errors
  main.go
Labels: ready-to-test, automated-backport

#2574 Automated backport of #2551: Add a few missing Expect() assertions
  pkg/globalnet/controllers/cluster_egressip_controller_test.go
  pkg/natdiscovery/natdiscovery_internal_test.go
Labels: ready-to-test, automated-backport

#2565 Automated backport of #2550: Pass functions to Eventually
  pkg/cableengine/healthchecker/healthchecker_test.go
Labels: ready-to-test, automated-backport

#2559 Disable dependabot PRs for parent-managed dependencies
  .github/dependabot.yml
Labels: ready-to-test
