Repository submariner-io/submariner, pull requests merged in 2023-04, with the labels that each got.

#2373 Define status subresource in globalnet CRDs
  pkg/apis/submariner.io/v1/types.go
Labels: backport-handled, ready-to-test

#2372 Bump admiral version
  go.mod
  go.sum
Labels: ready-to-test

#2367 Automated backport of #2349: Bump tim-actions/get-pr-commits for Node.js update
  .github/workflows/linting.yml
Labels: ready-to-test, automated-backport

#2389 Fix stale iptable rule and globalip leak
  pkg/globalnet/controllers/global_egressip_controller.go
  pkg/globalnet/controllers/types.go
Labels: ready-to-test

#2392 Automated backport of #2389: Fix stale iptable rule and globalip leak
  pkg/globalnet/controllers/global_egressip_controller.go
  pkg/globalnet/controllers/types.go
Labels: ready-to-test, automated-backport

#2358 Support for manual trigger of release image job
  .github/workflows/release.yml
Labels: ready-to-test

#2395 Fix failing code generation tests
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/natdiscovery/proto/natdiscovery.pb.go
Labels: ready-to-test

#2366 Automated backport of #2349: Bump tim-actions/get-pr-commits for Node.js update
  .github/workflows/linting.yml
Labels: ready-to-test, automated-backport

#2394 Automated backport of #2389: Fix stale iptable rule and globalip leak
  pkg/globalnet/controllers/global_egressip_controller.go
  pkg/globalnet/controllers/types.go
Labels: ready-to-test, automated-backport

#2398 Cache images for E2E
  .github/workflows/e2e-full.yml
  .github/workflows/e2e.yml
Labels: ready-to-test

#2399 Fix race when out-of-order RemoteEndpoint events are seen
  pkg/event/registry.go
  pkg/event/registry_test.go
  pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go
  pkg/routeagent_driver/handlers/kubeproxy/kp_iptables.go
  pkg/routeagent_driver/handlers/ovn/handler.go
Labels: backport, ready-to-test

#2229 Refactor `Makefile`
  Makefile
Labels: ready-to-test

#2403 Fix various Ginkgo idioms
  .golangci.yml
  pkg/endpoint/local_endpoint_test.go
  pkg/routeagent_driver/handlers/kubeproxy/vxlan_internal_test.go
  test/e2e/cluster/add_remove_cluster.go
  test/e2e/framework/dataplane.go
  test/e2e/framework/framework.go
Labels: ready-to-test

#2406 Configure dependabot for the release-0.15 branch
  .github/dependabot.yml
Labels: ready-to-test

#2404 Adjust to renamed syncer fields
  go.mod
  go.sum
  pkg/controllers/datastoresyncer/datastoresyncer.go
Labels: ready-to-test

#2417 Support packet-size as part of Globalnet e2e
  test/e2e/framework/dataplane.go
Labels: ready-to-test

#2393 Automated backport of #2389: Fix stale iptable rule and globalip leak
  pkg/globalnet/controllers/global_egressip_controller.go
  pkg/globalnet/controllers/types.go
Labels: release-note-needed, ready-to-test, automated-backport

#2419 Remove external-net+globalnet flake finder job
  .github/workflows/flake_finder.yml
Labels: automation, ready-to-test

#2418 Automated backport of #2416: Fix data race in syncer_test
  pkg/cableengine/syncer/syncer_test.go
Labels: ready-to-test, automated-backport

#2405 Automated backport of #2398: Cache images for E2E
  .github/workflows/e2e-full.yml
  .github/workflows/e2e.yml
Labels: ready-to-test, automated-backport

#2424 Automated backport of #2399: Fix race when out-of-order RemoteEndpoint events are seen
  pkg/event/registry.go
  pkg/event/registry_test.go
  pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go
  pkg/routeagent_driver/handlers/kubeproxy/kp_iptables.go
  pkg/routeagent_driver/handlers/ovn/handler.go
Labels: ready-to-test, automated-backport

#2423 Fix connection issues with RHEL9 GW nodes
  pkg/netlink/fake/netlink.go
  pkg/netlink/netlink.go
  pkg/routeagent_driver/handlers/kubeproxy/vxlan.go
Labels: backport, ready-to-test

#2430 Automated backport of #2399: Fix race when out-of-order RemoteEndpoint events are seen
  pkg/event/registry.go
  pkg/event/registry_test.go
  pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go
  pkg/routeagent_driver/handlers/kubeproxy/kp_iptables.go
Labels: ready-to-test, automated-backport

#2429 Automated backport of #2399: Fix race when out-of-order RemoteEndpoint events are seen
  pkg/event/registry.go
  pkg/event/registry_test.go
  pkg/routeagent_driver/handlers/kubeproxy/endpoint_handler.go
  pkg/routeagent_driver/handlers/kubeproxy/kp_iptables.go
  pkg/routeagent_driver/handlers/ovn/handler.go
Labels: ready-to-test, automated-backport

#2428 Ignore comments in proto-generated code
  .github/workflows/linting.yml
Labels: ready-to-test

#2431 Automated backport of #2417: Support packet-size as part of Globalnet e2e
  test/e2e/framework/dataplane.go
Labels: automated-backport

#2433 Fix vxlan cable driver issue on RHEL-9 Gateway nodes
  pkg/cable/vxlan/vxlan.go
  pkg/netlink/fake/netlink.go
  pkg/netlink/netlink.go
  pkg/routeagent_driver/handlers/kubeproxy/vxlan.go
Labels: backport, ready-to-test

#2436 Automated backport of #2433: Fix vxlan cable driver issue on RHEL-9 Gateway nodes
  pkg/cable/vxlan/vxlan.go
  pkg/netlink/fake/netlink.go
  pkg/netlink/netlink.go
  pkg/routeagent_driver/handlers/kubeproxy/vxlan.go
Labels: ready-to-test, automated-backport

#2437 Log connection status in Submariner gateway pod
  pkg/cableengine/healthchecker/pinger.go
Labels: backport, ready-to-test

#2438 Automated backport of #2437: Log connection status in Submariner gateway pod
  pkg/cableengine/healthchecker/pinger.go
Labels: automated-backport

#2446 Automated backport of #2443: Bump to Fedora 38
  package/Dockerfile.submariner-gateway
  package/Dockerfile.submariner-globalnet
  package/Dockerfile.submariner-networkplugin-syncer
  package/Dockerfile.submariner-route-agent
Labels: ready-to-test, automated-backport

#2448 Backport of #2363 on release-0.13
  pkg/cable/libreswan/libreswan.go
Labels: ready-to-test

#2449 Backport of #2363 on release-0.14
  pkg/cable/libreswan/libreswan.go
Labels: ready-to-test

#2450 Release notes for race condition fix in routeagent handlers
  release-notes/20230426-race-endpoints.md
Labels: backport, ready-to-test

#2451 Release notes for stale IPtable rule and globalIP leak
  release-notes/20230426-globalip-leak.md
Labels: backport

#2452 Release notes for RHEL-9 rp_filter setting
  release-notes/20230426-rhel9-fix.md
Labels: backport, ready-to-test

#2440 Automated backport of #2437: Log connection status in Submariner gateway pod
  pkg/cableengine/healthchecker/pinger.go
Labels: ready-to-test, automated-backport

#2434 Automated backport of #2423: Fix connection issues with RHEL9 GW nodes
  pkg/netlink/fake/netlink.go
  pkg/netlink/netlink.go
  pkg/routeagent_driver/handlers/kubeproxy/vxlan.go
Labels: ready-to-test, automated-backport

#2439 Automated backport of #2437: Log connection status in Submariner gateway pod
  pkg/cableengine/healthchecker/pinger.go
Labels: ready-to-test, automated-backport

#2453 Automated backport of #2433: Fix vxlan cable driver issue on RHEL-9 Gateway nodes
  pkg/cable/vxlan/vxlan.go
  pkg/netlink/fake/netlink.go
  pkg/netlink/netlink.go
  pkg/routeagent_driver/handlers/kubeproxy/vxlan.go
Labels: ready-to-test, automated-backport

#2462 Automated backport of #2452: Release notes for RHEL-9 rp_filter setting
  release-notes/20230426-rhel9-fix.md
Labels: ready-to-test, automated-backport

#2461 Automated backport of #2452: Release notes for RHEL-9 rp_filter setting
  release-notes/20230426-rhel9-fix.md
Labels: ready-to-test, automated-backport

#2456 Automated backport of #2450: Release notes for race condition fix in routeagent handlers
  release-notes/20230426-race-endpoints.md
Labels: ready-to-test, automated-backport

#2455 Automated backport of #2450: Release notes for race condition fix in routeagent handlers
  release-notes/20230426-race-endpoints.md
Labels: ready-to-test, automated-backport

#2458 Automated backport of #2451: Release notes for stale iptable rule and globalIP leak
  release-notes/20230426-globalip-leak.md
Labels: ready-to-test, automated-backport

#2459 Automated backport of #2451: Release notes for stale iptable rule and globalIP leak
  release-notes/20230426-globalip-leak.md
Labels: ready-to-test, automated-backport

#2460 Automated backport of #2452: Release notes for RHEL-9 rp_filter setting
  release-notes/20230426-rhel9-fix.md
Labels: ready-to-test, automated-backport

#2457 Automated backport of #2451: Release notes for stale iptable rule and globalIP leak
  release-notes/20230426-globalip-leak.md
Labels: ready-to-test, automated-backport
