Repository submariner-io/submariner, pull requests merged in 2023-08, with the labels that each got.

#2639 Automated backport of #2263: Skip endpoints from Broker with overlapping CIDRs
  pkg/controllers/datastoresyncer/datastoresyncer.go
Labels: ready-to-test, automated-backport

#2634 Add versions flag to binaries
  go.mod
  go.sum
  main.go
  pkg/globalnet/main.go
  pkg/networkplugin-syncer/main.go
  pkg/routeagent_driver/main.go
  pkg/versions/version.go
Labels: ready-to-test

#2643 Backport of #2263: Skip endpoints from Broker with overlapping CIDRs
  pkg/controllers/datastoresyncer/datastoresyncer.go
Labels: ready-to-test

#2644 Change the node_handler log to trace
  pkg/controllers/datastoresyncer/node_handler.go
Labels: ready-to-test

#2599 libreswan: Present --dpddelay if --dpdaction is specified
  pkg/cable/libreswan/libreswan.go
Labels: datapath, ready-to-test

#2621 Add controllers to program routes
  pkg/networkplugin-syncer/main.go
  pkg/routeagent_driver/constants/constants.go
  pkg/routeagent_driver/handlers/ovn/bridge.go
  pkg/routeagent_driver/handlers/ovn/connection.go
  pkg/routeagent_driver/handlers/ovn/env.go
  pkg/routeagent_driver/handlers/ovn/gateway_dataplane.go
  pkg/routeagent_driver/handlers/ovn/gateway_route_controller.go
  pkg/routeagent_driver/handlers/ovn/gateway_route_handler.go
  pkg/routeagent_driver/handlers/ovn/handler.go
  pkg/routeagent_driver/handlers/ovn/non_gateway_route_controller.go
  pkg/routeagent_driver/handlers/ovn/non_gateway_route_handler.go
  pkg/routeagent_driver/handlers/ovn/ovn_logical_routes.go
  pkg/routeagent_driver/handlers/ovn/uninstall.go
  pkg/routeagent_driver/main.go
Labels: ready-to-test

#2646 Honor publishNotReadyAddresses flag for headless services
  pkg/globalnet/controllers/ingress_pod_controller.go
  pkg/globalnet/controllers/service_export_controller_test.go
  pkg/globalnet/controllers/types.go
Labels: ready-to-test

#2638 Use LeasesResourceLock instead of ConfigMapsLeasesResourceLock
  main.go
Labels: ready-to-test

#2651 Enable forwarding on the submariner interfaces
  pkg/cable/vxlan/vxlan.go
  pkg/netlink/fake/netlink.go
  pkg/netlink/netlink.go
  pkg/routeagent_driver/handlers/kubeproxy/vxlan.go
Labels: datapath, priority:high, ready-to-test

#2652 Initialize stopCh in OVN controllers
  pkg/routeagent_driver/handlers/ovn/gateway_route_controller.go
  pkg/routeagent_driver/handlers/ovn/non_gateway_route_controller.go
Labels: ready-to-test

#2654 Automated backport of #2651: Enable forwarding on the submariner interfaces
  pkg/cable/vxlan/vxlan.go
  pkg/netlink/fake/netlink.go
  pkg/netlink/netlink.go
  pkg/routeagent_driver/handlers/kubeproxy/vxlan.go
Labels: automated-backport

#2655 Automated backport of #2651: Enable forwarding on the submariner interfaces
  pkg/cable/vxlan/vxlan.go
  pkg/netlink/fake/netlink.go
  pkg/netlink/netlink.go
  pkg/routeagent_driver/handlers/kubeproxy/vxlan.go
Labels: automated-backport

#2653 Fix golangci-lint 1.54.2 errors
  pkg/cable/wireguard/getconnections.go
  pkg/netlink/fake/netlink.go
Labels: ready-to-test

#2659 Ignore endpoint events after retrying couple of times
  pkg/event/controller/controller.go
  pkg/event/controller/endpoint_created.go
  pkg/event/controller/endpoint_removed.go
  pkg/event/controller/endpoint_updated.go
Labels: ready-to-test

#2656 Upgrade changes for OVN IC
  pkg/routeagent_driver/handlers/ovn/handler.go
  pkg/routeagent_driver/handlers/ovn/vsctl/vsctl.go
Labels: ready-to-test
