Repository submariner-io/submariner, pull requests merged in 2023-03, with the labels that each got.

#2323 Support in SM Globalnet for dual-stack clusters
  pkg/globalnet/controllers/gateway_monitor.go
  pkg/globalnet/controllers/global_ingressip_controller.go
  pkg/globalnet/main.go
Labels: ready-to-test, IPv6

#2326 Fix LinkNotFoundError error message
  pkg/netlink/netlink.go
  pkg/routeagent_driver/handlers/kubeproxy/routes_iface.go
Labels: ready-to-test

#2327 Release notes for dual-stack support
  release-notes/20230306-dual-stack.md
Labels: ready-to-test, IPv6

#2328 Use pointer utility functions instead of temporaries
  pkg/cable/wireguard/driver.go
  pkg/globalnet/controllers/cluster_egressip_controller.go
  pkg/networkplugin-syncer/handlers/ovn/ovn_logical_router_policy.go
Labels: technical-debt, ready-to-test

#2301 Set automated submariner-dependencies PR author
  .github/workflows/periodic.yml
Labels: automation, ready-to-test

#2336 More k8s.io pointer wrapping
  pkg/cable/libreswan/preferred_server.go
Labels: ready-to-test

#2344 Re-generate the client with a current generator
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/fake/fake_cluster.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/fake/fake_clusterglobalegressip.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/fake/fake_endpoint.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/fake/fake_gateway.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/fake/fake_globalegressip.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/fake/fake_globalingressip.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/submariner.io_client.go
  pkg/client/informers/externalversions/factory.go
  scripts/codegen
Labels: ready-to-test

#2349 Bump tim-actions GHAs for node updates
  .github/workflows/linting.yml
Labels: dependencies, ready-to-test

#2352 [Backport] Fix issues with gateway public-ip resolver (#2164)
  pkg/endpoint/local_endpoint.go
  pkg/endpoint/public_ip.go
  pkg/endpoint/public_ip_watcher.go
Labels: ready-to-test

#2346 log warning: VxLan cable-driver is supported only with no NAT deployments
  pkg/cable/vxlan/vxlan.go
Labels: ready-to-test

#2356 Ensure Gateway resource is deleted on shutdown
  main.go
  pkg/cableengine/syncer/syncer.go
  pkg/cableengine/syncer/syncer_test.go
  test/e2e/redundancy/gateway_failover.go
Labels: ready-to-test

#2353 [Backport] Public-ip resolver, change err log to debug (#2201)
  pkg/endpoint/public_ip.go
  pkg/endpoint/public_ip_internal_test.go
Labels: ready-to-test, automated-backport

#2357 Add profiling endpoints to the metrics servers
  main.go
  pkg/globalnet/main.go
Labels: ready-to-test

#2363 Cancel whack calls after 5s
  pkg/cable/libreswan/libreswan.go
Labels: backport, ready-to-test

#2365 Automated backport of #2349: Bump tim-actions/get-pr-commits for Node.js update
  .github/workflows/linting.yml
Labels: ready-to-test, automated-backport
