Repository submariner-io/submariner, pull requests merged in 2023-11, with the labels that each got.

#2780 Remove Twitter Together automation
  .github/workflows/twitter-together.yml
  tweets/README.md
  tweets/hello-world.tweet
Labels: automation, ready-to-test

#2793 use existing iptables APIs where possible
  pkg/globalnet/controllers/iptables/iface.go
  pkg/routeagent_driver/handlers/mtu/mtuhandler.go
Labels: ready-to-test

#2799 Override the ImageMagick license detection
  .lichen.yaml
Labels: ready-to-test

#2800 Bump to Fedora 39
  package/Dockerfile.submariner-gateway
  package/Dockerfile.submariner-globalnet
  package/Dockerfile.submariner-route-agent
Labels: ready-to-test

#2796 Update net to fix various CVEs
  go.mod
  go.sum
Labels: ready-to-test, security

#2801 Remove OVN Handler localEndpoint field
  pkg/routeagent_driver/handlers/ovn/handler.go
  pkg/routeagent_driver/handlers/ovn/host_networking.go
Labels: ready-to-test

#2802 Switch from stale app to stale GHA
  .github/stale.yml
  .github/workflows/stale.yml
Labels: automation, ready-to-test

#2804 Remove 0.8.0 upgrade code and test
  pkg/controllers/datastoresyncer/datastore_0.8.0_upgrade_test.go
  pkg/controllers/datastoresyncer/datastoresyncer.go
Labels: ready-to-test

#2805 Pass host name to gateway monitor
  pkg/globalnet/controllers/gateway_monitor.go
  pkg/globalnet/controllers/gateway_monitor_test.go
  pkg/globalnet/controllers/types.go
  pkg/globalnet/main.go
Labels: ready-to-test

#2807 Bump admiral and adjust to changes
  go.mod
  go.sum
  pkg/controllers/datastoresyncer/datastore_cluster_sync_test.go
  pkg/controllers/datastoresyncer/datastore_endpoint_sync_test.go
  pkg/controllers/datastoresyncer/datastoresyncer_suite_test.go
  pkg/event/controller/controller_test.go
  pkg/gateway/gateway_test.go
  pkg/globalnet/controllers/controllers_suite_test.go
  pkg/globalnet/controllers/gateway_monitor_test.go
  pkg/globalnet/controllers/global_ingressip_controller.go
  pkg/globalnet/controllers/uninstall.go
Labels: ready-to-test

#2809 Exclude code from SonarCloud analysis
  sonar-project.properties
Labels: ready-to-test
