Repository submariner-io/submariner, pull requests merged in 2023-09, with the labels that each got.

#2662 Move the OVN-NBDB address discovery to route-agent
  pkg/routeagent_driver/handlers/ovn/connection.go
  pkg/routeagent_driver/handlers/ovn/constants.go
  pkg/routeagent_driver/handlers/ovn/env.go
Labels: ready-to-test

#2675 Delete legacy non-IC static routes
  pkg/routeagent_driver/handlers/ovn/ovn_logical_routes.go
Labels: ready-to-test

#2668 Only release images on submariner-io
  .github/workflows/release.yml
Labels: automation, ready-to-test

#2680 Automated backport of #2599: libreswan: Present --dpddelay if --dpdaction is specified
  pkg/cable/libreswan/libreswan.go
Labels: ready-to-test, automated-backport

#2041 Add CodeQL variant analysis scanning
  .github/workflows/linting.yml
  .github/workflows/report.yml
Labels: automation, ready-to-test

#2683 Automated backport of #2681: Fix e2e failures seen with OCP OVN-IC deployments
  pkg/routeagent_driver/handlers/ovn/gateway_dataplane.go
Labels: automated-backport

#2682 Refactor the ovn network discovery code
  pkg/routeagent_driver/handlers/ovn/connection.go
  pkg/routeagent_driver/handlers/ovn/constants.go
Labels: backport, ready-to-test

#2684 Automated backport of #2682: Refactor the ovn network discovery code
  pkg/routeagent_driver/handlers/ovn/connection.go
  pkg/routeagent_driver/handlers/ovn/constants.go
Labels: ready-to-test, automated-backport

#2685 Configure dependabot for the release-0.16 branch
  .github/dependabot.yml
Labels: ready-to-test, automated

#2706 Fix flaky datastore syncer unit test
  pkg/controllers/datastoresyncer/datastore_endpoint_sync_test.go
Labels: ready-to-test

#2708 Fix IPsec whack returning exit status 33
  pkg/cable/libreswan/libreswan.go
Labels: backport, ready-to-test

#2711 Automated backport of #2708: Fix IPsec whack returning exit status 33
  pkg/cable/libreswan/libreswan.go
Labels: ready-to-test, automated-backport

#2712 Automated backport of #2708: Fix IPsec whack returning exit status 33
  pkg/cable/libreswan/libreswan.go
Labels: ready-to-test, automated-backport

#2710 Retry IPsec connections when there are any whack errors
  pkg/cable/libreswan/libreswan.go
Labels: backport, ready-to-test

#2713 Automated backport of #2708: Fix IPsec whack returning exit status 33
  pkg/cable/libreswan/libreswan.go
Labels: ready-to-test, automated-backport

#2714 Automated backport of #2708: Fix IPsec whack returning exit status 33
  pkg/cable/libreswan/libreswan.go
Labels: ready-to-test, automated-backport

#2717 Automated backport of #2710: Retry IPsec connections when there are any whack errors
  pkg/cable/libreswan/libreswan.go
Labels: ready-to-test, automated-backport

#2718 Automated backport of #2710: Retry IPsec connections when there are any whack errors
  pkg/cable/libreswan/libreswan.go
Labels: ready-to-test, automated-backport

#2719 Allow the route agent to wait for node readiness
  go.mod
  go.sum
  pkg/routeagent_driver/environment/env.go
  pkg/routeagent_driver/main.go
Labels: backport, ready-to-test

#2720 Remove the MTU workaround used for OVN load-balancers
  pkg/routeagent_driver/handlers/ovn/gateway_dataplane.go
Labels: ready-to-test

#2721 Split stop and uninstall in RA handlers
  pkg/event/controller/controller.go
  pkg/event/handler.go
  pkg/event/registry.go
  pkg/event/registry_test.go
  pkg/event/testing/testing.go
  pkg/routeagent_driver/handlers/calico/ippool_handler.go
  pkg/routeagent_driver/handlers/kubeproxy/uninstall.go
  pkg/routeagent_driver/handlers/mtu/mtuhandler.go
  pkg/routeagent_driver/handlers/ovn/uninstall.go
  pkg/routeagent_driver/main.go
Labels: ready-to-test
