Repository submariner-io/submariner, pull requests merged in 2023-07, with the labels that each got.

#2543 Shortening datapath downtime for libreswan cable
  pkg/cable/libreswan/libreswan.go
Labels: datapath, backport, ready-to-test

#2596 Automated backport of #2543: Shortening datapath downtime for libreswan cable
  pkg/cable/libreswan/libreswan.go
Labels: ready-to-test, automated-backport

#2595 Use k8s.io/utils set instead of apimachinery
  go.mod
  go.sum
  pkg/endpoint/local_endpoint.go
  pkg/event/registry.go
  pkg/globalnet/controllers/gateway_monitor.go
  pkg/globalnet/controllers/ingress_pod_controller.go
  pkg/globalnet/controllers/types.go
  pkg/ipam/ippool_test.go
  pkg/ipset/fake/ipset.go
  pkg/iptables/adapter.go
  pkg/iptables/fake/iptables.go
  pkg/networkplugin-syncer/handlers/ovn/ovn_logical_router_policy.go
  pkg/networkplugin-syncer/handlers/ovn/ovn_logical_router_static_route.go
  pkg/networkplugin-syncer/handlers/ovn/ovn_submariner_infrastructure.go
  pkg/networkplugin-syncer/handlers/ovn/subnets.go
  pkg/networkplugin-syncer/handlers/ovn/subnets_internal_test.go
  pkg/routeagent_driver/handlers/kubeproxy/kp_iptables.go
  pkg/routeagent_driver/handlers/ovn/host_networking.go
  pkg/routeagent_driver/handlers/ovn/south_rules.go
  pkg/routeagent_driver/handlers/ovn/subnets.go
Labels: ready-to-test

#2598 Automated backport of #2543: Shortening datapath downtime for libreswan cable
  pkg/cable/libreswan/libreswan.go
Labels: ready-to-test, automated-backport

#2610 Add GatewayRouteList and NonGatewayRouteList to scheme
  pkg/apis/submariner.io/v1/register.go
Labels: ready-to-test

#2552 log submariner component's version on startup
  Makefile
  main.go
  pkg/globalnet/main.go
  pkg/networkplugin-syncer/main.go
  pkg/routeagent_driver/main.go
  pkg/versions/version.go
Labels: backport, ready-to-test

#2614 Consider Pluto status on Libreswan GetConnections
  pkg/cable/libreswan/libreswan.go
Labels: backport, ready-to-test

#2618 Automated backport of #2614: Consider Pluto status on Libreswan GetConnections
  pkg/cable/libreswan/libreswan.go
Labels: ready-to-test, automated-backport

#2616 Automated backport of #2614: Consider Pluto status on Libreswan GetConnections
  pkg/cable/libreswan/libreswan.go
Labels: ready-to-test, automated-backport

#2576 Automate calico ippools creation by routeagent
  go.mod
  go.sum
  pkg/routeagent_driver/handlers/calico/ippool_handler.go
  pkg/routeagent_driver/main.go
Labels: release-note-needed, ready-to-test

#2622 Switch to generic k8s.io/utils/ptr
  go.mod
  go.sum
  pkg/cable/libreswan/preferred_server.go
  pkg/cable/wireguard/driver.go
  pkg/globalnet/controllers/cluster_egressip_controller.go
  pkg/networkplugin-syncer/handlers/ovn/ovn_logical_router_policy.go
Labels: ready-to-test

#2620 Bump admiral and adjust to changes
  go.mod
  go.sum
  pkg/controllers/datastoresyncer/datastoresyncer.go
Labels: ready-to-test

#2569 Add handlers to create GatewayRoute and NonGatewayRoute CRs
  pkg/routeagent_driver/constants/constants.go
  pkg/routeagent_driver/handlers/ovn/gateway_route_handler.go
  pkg/routeagent_driver/handlers/ovn/non_gateway_route_handler.go
  pkg/routeagent_driver/handlers/ovn/utils.go
  pkg/routeagent_driver/main.go
Labels: ready-to-test

#2487 Rework status Conditions for Globalnet resources
  pkg/globalnet/controllers/base_controllers.go
  pkg/globalnet/controllers/cluster_egressip_controller.go
  pkg/globalnet/controllers/cluster_egressip_controller_test.go
  pkg/globalnet/controllers/controllers_suite_test.go
  pkg/globalnet/controllers/global_egressip_controller.go
  pkg/globalnet/controllers/global_egressip_controller_test.go
  pkg/globalnet/controllers/global_ingressip_controller.go
  pkg/globalnet/controllers/global_ingressip_controller_test.go
  pkg/globalnet/controllers/service_export_controller_test.go
Labels: ready-to-test, blocked-on-rereview
