Repository submariner-io/submariner, pull requests merged in 2023-02, with the labels that each got.

#2272 Fix intermittent globalnet unit tests failures
  pkg/globalnet/controllers/global_ingressip_controller_test.go
  pkg/globalnet/controllers/service_export_controller_test.go
Labels: technical-debt, ready-to-test

#2275 Fix stale Globalnet internal services
  pkg/globalnet/controllers/gateway_monitor.go
  pkg/globalnet/controllers/uninstall.go
Labels: ready-to-test

#2274 Ignore k8s dependencies included with client-go
  .github/dependabot.yml
Labels: ready-to-test, maintenance

#2283 Modifying the argument passed to the clientcmd.BuildConfigFromFlags method
  pkg/event/controller/controller.go
Labels: ready-to-test

#2173 Add GHA to periodically integrate submariner-io/*
  .github/workflows/periodic.yml
Labels: automation, ready-to-test

#2284 Update readme
  README.md
Labels: ready-to-test

#2300 Bump golang.org/x/net to 0.7.0
  go.mod
  go.sum
Labels: dependencies, ready-to-test

#2302 Bump go-restful to 2.16.0
  go.mod
  go.sum
Labels: dependencies, ready-to-test
