Repository submariner-io/submariner, pull requests merged in 2023-01, with the labels that each got.

#2184 Handle the case of multiple IP addresses for publicDNSIP
  pkg/endpoint/public_ip.go
Labels: ready-to-test

#2222 Allow re-running the plugin script
  scripts/e2e/external/utils
Labels: ready-to-test

#2244 Automated backport of #1941: Add constant for Flannel CNI #2036: Declare constant for kindnet
  pkg/cni/plugins.go
  pkg/routeagent_driver/handlers/kubeproxy/kp_iptables.go
Labels: ready-to-test, automated-backport

#2245 Skip IPv6 node addresses while adding fdb entries
  pkg/routeagent_driver/handlers/kubeproxy/node_handler.go
Labels: ready-to-test, IPv6

#2232 Add FIPS status test
  go.mod
  go.sum
  test/e2e/dataplane/fips_status.go
Labels: ready-to-test

#2252 Move FIPS E2E test to new compliance category
  test/e2e/compliance/fips.go
  test/e2e/e2e_test.go
Labels: ready-to-test

#2250 Skip processing IPv6 addresses in mtu_handler
  pkg/routeagent_driver/handlers/mtu/mtuhandler.go
Labels: ready-to-test, IPv6

#2263 Skip endpoints from Broker with overlapping CIDRs
  pkg/controllers/datastoresyncer/datastoresyncer.go
Labels: ready-to-test

#2271 Change frequency of dependabot gh-action check to monthly
  .github/dependabot.yml
Labels: ready-to-test, maintenance
