Repository submariner-io/submariner, pull requests merged in 2023-10, with the labels that each got.

#2738 Fix log message from nodeHandler
  pkg/controllers/datastoresyncer/node_handler.go
Labels: backport, ready-to-test

#2741 Automated backport of #2738: Fix log message from nodeHandler
  pkg/controllers/datastoresyncer/node_handler.go
Labels: ready-to-test, automated-backport

#2740 Automated backport of #2738: Fix log message from nodeHandler
  pkg/controllers/datastoresyncer/node_handler.go
Labels: ready-to-test, automated-backport

#2742 Use generic resource handling
  go.mod
  go.sum
  pkg/cableengine/syncer/syncer.go
  pkg/globalnet/controllers/controllers_suite_test.go
  pkg/globalnet/controllers/global_ingressip_controller.go
  pkg/globalnet/controllers/uninstall.go
  pkg/routeagent_driver/handlers/ovn/gateway_route_handler.go
  pkg/routeagent_driver/handlers/ovn/non_gateway_route_handler.go
Labels: ready-to-test

#2752 On route agent startup, delete invalid directories
  pkg/routeagent_driver/main.go
Labels: backport, ready-to-test

#2753 Automated backport of #2752: On route agent startup, delete invalid directories
  pkg/routeagent_driver/main.go
Labels: ready-to-test, automated-backport

#2756 Use Gingko spec labels in E2E tests
  go.mod
  go.sum
  test/e2e/compliance/fips.go
  test/e2e/dataplane/gateway_status.go
  test/e2e/dataplane/tcp_gn_pod_connectivity.go
  test/e2e/dataplane/tcp_pod_connectivity.go
  test/e2e/redundancy/gateway_failover.go
  test/e2e/redundancy/route_agent_restart.go
Labels: ready-to-test

#2760 Gateway Run should return error on uninstall
  pkg/cableengine/fake/cableengine.go
  pkg/gateway/gateway.go
  pkg/gateway/gateway_test.go
Labels: ready-to-test

#2765 Automated backport of #2748: Refactor bulk of main.go to a new gateway package
  main.go
  pkg/cableengine/fake/cableengine.go
  pkg/cableengine/syncer/syncer.go
  pkg/endpoint/local_endpoint.go
  pkg/gateway/gateway.go
  pkg/gateway/gateway_suite_test.go
  pkg/gateway/gateway_test.go
Labels: automated-backport

#2761 Allow halting on certificate errors
  go.mod
  go.sum
  main.go
  pkg/types/types.go
Labels: backport, ready-to-test

#2768 Automated backport of #2761: Allow halting on certificate errors
  go.mod
  go.sum
  main.go
  pkg/types/types.go
Labels: ready-to-test, automated-backport

#2769 Fix new linting errors
  pkg/apis/submariner.io/v1/endpoint.go
  pkg/endpoint/public_ip_internal_test.go
  pkg/netlink/netlink.go
Labels: ready-to-test

#2770 Fix lint error in wireguard
  pkg/cable/wireguard/getconnections.go
Labels: ready-to-test

#2767 Remove release-notes files
  release-notes/20221103-mss-clamp.md
  release-notes/20230306-dual-stack.md
  release-notes/20230426-globalip-leak.md
  release-notes/20230426-race-endpoints.md
  release-notes/20230426-rhel9-fix.md
  release-notes/20230508-ovn-gw-node.md
Labels: ready-to-test

#2772 Only update local Endpoint when setting HealthCheckIP
  main.go
  pkg/controllers/datastoresyncer/datastore_endpoint_sync_test.go
  pkg/controllers/datastoresyncer/datastoresyncer.go
  pkg/controllers/datastoresyncer/node_handler.go
Labels: backport, ready-to-test

#2773 Automated backport of #2772: Only update local Endpoint when setting HealthCheckIP
  main.go
  pkg/controllers/datastoresyncer/datastore_endpoint_sync_test.go
  pkg/controllers/datastoresyncer/datastoresyncer.go
  pkg/controllers/datastoresyncer/node_handler.go
Labels: ready-to-test, automated-backport

#2766 Delete Calico IPPools when Submariner uninstalled
  pkg/routeagent_driver/handlers/calico/ippool_handler.go
Labels: backport, ready-to-test

#2774 Automated backport of #2766: Delete Calico IPPools when Submariner uninstalled
  pkg/routeagent_driver/handlers/calico/ippool_handler.go
Labels: ready-to-test, automated-backport

#2776 Automated backport of #2760: Gateway Run should return error on uninstall
  pkg/cableengine/fake/cableengine.go
  pkg/gateway/gateway.go
  pkg/gateway/gateway_test.go
Labels: ready-to-test, automated-backport

#2778 Pass ctx to datastoreSyncer Start method
  go.mod
  go.sum
  main.go
  pkg/cableengine/syncer/syncer.go
  pkg/cableengine/syncer/syncer_test.go
  pkg/controllers/datastoresyncer/datastore_cluster_sync_test.go
  pkg/controllers/datastoresyncer/datastore_endpoint_sync_test.go
  pkg/controllers/datastoresyncer/datastoresyncer.go
  pkg/controllers/datastoresyncer/datastoresyncer_suite_test.go
  pkg/controllers/datastoresyncer/node_handler.go
  pkg/gateway/gateway.go
  pkg/gateway/gateway_test.go
  pkg/globalnet/controllers/base_controllers.go
  pkg/globalnet/controllers/node_controller.go
  pkg/pod/pod.go
Labels: backport, ready-to-test

#2779 Automated backport of #2778: Pass ctx to datastoreSyncer Start method
  go.mod
  go.sum
  main.go
  pkg/cableengine/syncer/syncer.go
  pkg/cableengine/syncer/syncer_test.go
  pkg/controllers/datastoresyncer/datastore_cluster_sync_test.go
  pkg/controllers/datastoresyncer/datastore_endpoint_sync_test.go
  pkg/controllers/datastoresyncer/datastoresyncer.go
  pkg/controllers/datastoresyncer/datastoresyncer_suite_test.go
  pkg/controllers/datastoresyncer/node_handler.go
  pkg/gateway/gateway.go
  pkg/gateway/gateway_test.go
  pkg/globalnet/controllers/base_controllers.go
  pkg/globalnet/controllers/node_controller.go
  pkg/pod/pod.go
Labels: ready-to-test, automated-backport
