Repository submariner-io/submariner, pull requests merged in 2024-02, with the labels that each got.

#2892 Use the Admiral metrics/profile helper
  go.mod
  go.sum
  main.go
  pkg/globalnet/controllers/types.go
  pkg/globalnet/main.go
  pkg/routeagent_driver/environment/env.go
  pkg/routeagent_driver/main.go
  pkg/types/types.go
Labels: metrics, ready-to-test

#2899 Add code owners for go.mod/go.sum
  CODEOWNERS
  CODEOWNERS.in
Labels: ready-to-test

#2902 Use K8s 1.29 as latest in E2E
  .github/workflows/e2e.yml
  .github/workflows/flake_finder.yml
Labels: ready-to-test

#2903 Add Yossi as committer to go.mod and go.sum
  CODEOWNERS
  CODEOWNERS.in
Labels: backport, ready-to-test

#2897 Workaround for ROKS datapath configuration
  pkg/routeagent_driver/handlers/calico/calico_suite_test.go
  pkg/routeagent_driver/handlers/calico/ippool_handler.go
  pkg/routeagent_driver/handlers/calico/ippool_handler_test.go
  pkg/routeagent_driver/main.go
Labels: dependent, ready-to-test

#2904 Add unit tests for ROKS support in Calico RA handler
  pkg/routeagent_driver/handlers/calico/calico_suite_test.go
  pkg/routeagent_driver/handlers/calico/ippool_handler.go
  pkg/routeagent_driver/handlers/calico/ippool_handler_test.go
Labels: ready-to-test

#2906 [0.16] Backport code owner updates
  CODEOWNERS
  CODEOWNERS.in
Labels: ready-to-test

#2907 [0.15] Backport code owner updates
  CODEOWNERS
  CODEOWNERS.in
Labels: ready-to-test

#2905 [0.17] Backport code owner updates
  CODEOWNERS
  CODEOWNERS.in
Labels: ready-to-test

#2908 Automated backport of #2897: Workaround for ROKS datapath configuration
  pkg/routeagent_driver/handlers/calico/calico_suite_test.go
  pkg/routeagent_driver/handlers/calico/ippool_handler.go
  pkg/routeagent_driver/handlers/calico/ippool_handler_test.go
  pkg/routeagent_driver/main.go
Labels: ready-to-test, automated-backport

#2909 Update generated code with 1.29 codegen
  pkg/client/applyconfiguration/internal/internal.go
  pkg/client/applyconfiguration/submariner.io/v1/cluster.go
  pkg/client/applyconfiguration/submariner.io/v1/clusterglobalegressip.go
  pkg/client/applyconfiguration/submariner.io/v1/clusterglobalegressipspec.go
  pkg/client/applyconfiguration/submariner.io/v1/clusterspec.go
  pkg/client/applyconfiguration/submariner.io/v1/connection.go
  pkg/client/applyconfiguration/submariner.io/v1/endpoint.go
  pkg/client/applyconfiguration/submariner.io/v1/endpointspec.go
  pkg/client/applyconfiguration/submariner.io/v1/gateway.go
  pkg/client/applyconfiguration/submariner.io/v1/gatewayroute.go
  pkg/client/applyconfiguration/submariner.io/v1/gatewaystatus.go
  pkg/client/applyconfiguration/submariner.io/v1/globalegressip.go
  pkg/client/applyconfiguration/submariner.io/v1/globalegressipspec.go
  pkg/client/applyconfiguration/submariner.io/v1/globalegressipstatus.go
  pkg/client/applyconfiguration/submariner.io/v1/globalingressip.go
  pkg/client/applyconfiguration/submariner.io/v1/globalingressipspec.go
  pkg/client/applyconfiguration/submariner.io/v1/globalingressipstatus.go
  pkg/client/applyconfiguration/submariner.io/v1/latencyrttspec.go
  pkg/client/applyconfiguration/submariner.io/v1/nongatewayroute.go
  pkg/client/applyconfiguration/submariner.io/v1/routepolicyspec.go
  pkg/client/applyconfiguration/utils.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/cluster.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/clusterglobalegressip.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/endpoint.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/fake/fake_cluster.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/fake/fake_clusterglobalegressip.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/fake/fake_endpoint.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/fake/fake_gateway.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/fake/fake_gatewayroute.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/fake/fake_globalegressip.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/fake/fake_globalingressip.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/fake/fake_nongatewayroute.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/gateway.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/gatewayroute.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/globalegressip.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/globalingressip.go
  pkg/client/clientset/versioned/typed/submariner.io/v1/nongatewayroute.go
  pkg/client/informers/externalversions/factory.go
  scripts/codegen
Labels: ready-to-test

#2912 Ignore unused parameters
  pkg/cableengine/cableengine_test.go
  pkg/cableengine/healthchecker/pinger.go
  pkg/cableengine/syncer/syncer_test.go
  pkg/controllers/tunnel/tunnel_test.go
  pkg/natdiscovery/test_utils.go
  pkg/routeagent_driver/handlers/kubeproxy/sync_handler_test.go
  pkg/routeagent_driver/handlers/ovn/handler_test.go
Labels: ready-to-test
