Repository submariner-io/submariner, pull requests merged in 2024-09, with the labels that each got.

#3145 Switch to admiral IPAM
  go.mod
  go.sum
  pkg/globalnet/controllers/base_controllers.go
  pkg/globalnet/controllers/cluster_egressip_controller.go
  pkg/globalnet/controllers/cluster_egressip_controller_test.go
  pkg/globalnet/controllers/controllers_suite_test.go
  pkg/globalnet/controllers/gateway_controller.go
  pkg/globalnet/controllers/gateway_controller_test.go
  pkg/globalnet/controllers/gateway_monitor.go
  pkg/globalnet/controllers/global_egressip_controller.go
  pkg/globalnet/controllers/global_egressip_controller_test.go
  pkg/globalnet/controllers/global_ingressip_controller.go
  pkg/globalnet/controllers/global_ingressip_controller_test.go
  pkg/globalnet/controllers/service_export_controller_test.go
  pkg/globalnet/controllers/types.go
  pkg/globalnet/metrics/metrics.go
  pkg/ipam/ipam_suite_test.go
  pkg/ipam/ippool.go
  pkg/ipam/ippool_test.go
Labels: ready-to-test

#3077 Add route-agent-healthcheck
  pkg/apis/submariner.io/v1/types.go
  pkg/cableengine/healthchecker/healthchecker.go
  pkg/cableengine/healthchecker/healthchecker_test.go
  pkg/cableengine/syncer/syncer.go
  pkg/cableengine/syncer/syncer_test.go
  pkg/pinger/fake/pinger.go
  pkg/pinger/pinger.go
  pkg/pinger/pinger_test.go
  pkg/pinger/statistics.go
  pkg/pinger/statistics_internal_test.go
  pkg/routeagent_driver/handlers/healthchecker/healthchecker.go
  pkg/routeagent_driver/main.go
Labels: ready-to-test

#3156 Explicitly disable BGP export for Calico IPPools
  pkg/routeagent_driver/handlers/calico/ippool_handler.go
Labels: backport, ready-to-test

#3161 Automated backport of #3156: Explicitly disable BGP export for Calico IPPools
  pkg/routeagent_driver/handlers/calico/ippool_handler.go
Labels: ready-to-test, automated-backport

#3162 Automated backport of #3156: Explicitly disable BGP export for Calico IPPools
  pkg/routeagent_driver/handlers/calico/ippool_handler.go
Labels: ready-to-test, automated-backport

#3144 Rework integer type selection
  pkg/apis/submariner.io/v1/endpoint.go
  pkg/cableengine/healthchecker/healthchecker.go
  pkg/natdiscovery/proto/natdiscovery.pb.go
  pkg/natdiscovery/proto/natdiscovery.proto
  pkg/natdiscovery/request_handle.go
  pkg/natdiscovery/request_handle_internal_test.go
  pkg/natdiscovery/request_send.go
  pkg/natdiscovery/request_send_internal_test.go
  pkg/pinger/pinger.go
  pkg/pinger/statistics.go
  pkg/pinger/statistics_internal_test.go
  pkg/routeagent_driver/handlers/healthchecker/healthchecker.go
  pkg/routeagent_driver/handlers/healthchecker/healthchecker_test.go
  pkg/types/types.go
  test/e2e/framework/dataplane.go
Labels: ready-to-test

#3166 Add RouteAgent CRDs to known types for scheme
  pkg/apis/submariner.io/v1/register.go
Labels: ready-to-test

#3170 Bump to Fedora 40
  package/Dockerfile.submariner-gateway
  package/Dockerfile.submariner-globalnet
  package/Dockerfile.submariner-route-agent
Labels: ready-to-test
