Repository submariner-io/submariner, pull requests merged in 2024-05, with the labels that each got.

#2994 Switch to math/rand/v2
  pkg/endpoint/public_ip.go
Labels: ready-to-test

#3002 Fix error prepending rule in createGlobalnetChains
  pkg/globalnet/controllers/gateway_monitor.go
  pkg/packetfilter/adapter_test.go
  pkg/packetfilter/fake/packetfilter.go
Labels: ready-to-test

#3004 Adjust to golangci-lint 1.58.0
  .golangci.yml
  pkg/natdiscovery/natdiscovery.go
Labels: ready-to-test

#3005 Drop crypto/rand for NAT request counters
  pkg/natdiscovery/natdiscovery.go
Labels: ready-to-test

#3009 Globalnet not running in E2E
  .github/workflows/e2e.yml
Labels: backport, ready-to-test

#3012 Automated backport of #3009: Globalnet not running in E2E
  .github/workflows/e2e.yml
Labels: ready-to-test, automated-backport

#3013 De-duplicate CNI discovery code
  pkg/cable/vxlan/vxlan.go
  pkg/cable/vxlan/vxlan_test.go
  pkg/cni/cni_iface.go
  pkg/endpoint/local_endpoint.go
  pkg/endpoint/local_endpoint_test.go
  pkg/globalnet/controllers/controllers_suite_test.go
  pkg/globalnet/controllers/node_controller.go
  pkg/routeagent_driver/handlers/kubeproxy/kp_packetfilter.go
  pkg/routeagent_driver/handlers/kubeproxy/sync_handler_test.go
Labels: ready-to-test

#3014 Adjust to golangci-lint 1.58.2
  pkg/natdiscovery/natdiscovery.go
Labels: ready-to-test

#3016 Enable retry when setting passive label for standby GW pod
  pkg/gateway/gateway.go
Labels: ready-to-test

#3018 Adjustments to retry when setting passive GW on leadership lost
  go.mod
  go.sum
  pkg/gateway/gateway.go
  pkg/gateway/gateway_test.go
Labels: ready-to-test

#3022 Pass ctx to onStoppedLeading in gatewayType
  pkg/gateway/gateway.go
Labels: ready-to-test

#3026 Use RouteAddOrReplace in kube proxy handler
  pkg/routeagent_driver/handlers/kubeproxy/routes_iface.go
Labels: ready-to-test

#3030 Skip gateway failover E2E test for wireguard
  pkg/cable/wireguard/driver.go
  pkg/cable/wireguard/getconnections.go
  test/e2e/redundancy/gateway_failover.go
Labels: ready-to-test
