Repository submariner-io/submariner, pull requests merged in 2024-01, with the labels that each got.

#2832 Eliminate duplicate all-defaults E2E run, add K8s E2E, standardize GHA config
  .github/workflows/e2e.yml
  .github/workflows/flake_finder.yml
Labels: automation, ready-to-test

#2866 Split tools dependencies to a separate module
  Makefile
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: ready-to-test

#2865 Fix ovn-failover
  pkg/routeagent_driver/handlers/ovn/gateway_route_handler.go
  pkg/routeagent_driver/handlers/ovn/gateway_route_handler_test.go
  pkg/routeagent_driver/handlers/ovn/non_gateway_route_handler.go
  pkg/routeagent_driver/handlers/ovn/non_gateway_route_handler_test.go
Labels: release-note-needed, ready-to-test

#2870 Automated backport of #2865: Fix race condition in ovn-kubernetes CNI
  pkg/routeagent_driver/handlers/ovn/gateway_route_handler.go
  pkg/routeagent_driver/handlers/ovn/non_gateway_route_handler.go
Labels: release-note-needed, ready-to-test, automated-backport

#2880 Automated backport of #2348: Bump the base image to Fedora 37 #2443: Bump to Fedora 38
  package/Dockerfile.submariner-gateway
  package/Dockerfile.submariner-globalnet
  package/Dockerfile.submariner-networkplugin-syncer
  package/Dockerfile.submariner-route-agent
Labels: ready-to-test, automated-backport

#2885 Add Makefile.shipyard to .gitignore
  .gitignore
Labels: ready-to-test

#2888 Ensure packetfilter driver is set before uninstall
  pkg/globalnet/main.go
Labels: ready-to-test
