Repository submariner-io/submariner, pull requests merged in 2024-03, with the labels that each got.

#2926 Add dependabot config for release-0.17
  .github/dependabot.yml
Labels: ready-to-test

#2924 Adjustments to the fake packetfilter implementation
  pkg/packetfilter/fake/packetfilter.go
Labels: ready-to-test

#2933 Adjust chain rule implementation in fake packetfilter
  pkg/globalnet/controllers/cluster_egressip_controller_test.go
  pkg/globalnet/controllers/controllers_suite_test.go
  pkg/globalnet/controllers/gateway_monitor_test.go
  pkg/globalnet/controllers/global_egressip_controller_test.go
  pkg/globalnet/controllers/global_ingressip_controller_test.go
  pkg/globalnet/controllers/node_controller_test.go
  pkg/globalnet/controllers/service_controller_test.go
  pkg/globalnet/controllers/service_export_controller_test.go
  pkg/packetfilter/fake/packetfilter.go
Labels: ready-to-test

#2935 Only fail builds for high+ vulns
  .github/workflows/linting.yml
Labels: backport, ready-to-test

#2940 Automated backport of #2935: Only fail builds for high+ vulns
  .github/workflows/linting.yml
Labels: ready-to-test, automated-backport

#2941 Automated backport of #2935: Only fail builds for high+ vulns
  .github/workflows/linting.yml
Labels: ready-to-test, automated-backport

#2945 Add unit tests for the libreswan cable driver
  .gitignore
  go.mod
  go.sum
  pkg/cable/libreswan/libreswan.go
  pkg/cable/libreswan/libreswan_internal_test.go
  pkg/cable/libreswan/libreswan_suite_test.go
Labels: ready-to-test

#2947 Use proxy vars
  main.go
  pkg/endpoint/public_ip.go
Labels: ready-to-test

#2950 Automated backport of #2892: Use the Admiral metrics/profile helper
  go.mod
  go.sum
  main.go
  pkg/globalnet/controllers/types.go
  pkg/globalnet/main.go
  pkg/routeagent_driver/environment/env.go
  pkg/routeagent_driver/main.go
  pkg/types/types.go
Labels: automated-backport

#2951 Fix linting errors with golangci-lint v1.57.1
  pkg/cable/libreswan/libreswan.go
  pkg/event/registry.go
  pkg/globalnet/controllers/global_egressip_controller.go
  pkg/routeagent_driver/handlers/calico/ippool_handler.go
Labels: ready-to-test
