Repository submariner-io/submariner, pull requests merged in 2025-03, with the labels that each got.

#3315 Include the main package and embedded files in pkgdeps
  Makefile
Labels: ready-to-test

#3316 Disable UPX for binaries shipped in images
  package/Dockerfile.submariner-gateway
  package/Dockerfile.submariner-globalnet
  package/Dockerfile.submariner-route-agent
Labels: ready-to-test

#3328 Exclude files from sonar
  sonar-project.properties
Labels: ready-to-test

#3333 Add nftables binary to GlobalNet and RouteAgent images
  package/Dockerfile.submariner-globalnet
  package/Dockerfile.submariner-route-agent
Labels: ready-to-test

#3332 Replace deprecated sonarsource/sonarcloud-github-action
  .github/workflows/report.yml
Labels: ready-to-test

#3320 Add IP family support to cableengine
  pkg/apis/submariner.io/v1/types.go
  pkg/cable/driver.go
  pkg/cable/fake/driver.go
  pkg/cable/libreswan/libreswan.go
  pkg/cable/libreswan/libreswan_internal_test.go
  pkg/cable/metrics.go
  pkg/cable/vxlan/vxlan.go
  pkg/cable/vxlan/vxlan_test.go
  pkg/cable/wireguard/driver.go
  pkg/cable/wireguard/getconnections.go
  pkg/cableengine/cableengine.go
  pkg/cableengine/cableengine_test.go
  pkg/cableengine/syncer/syncer.go
  pkg/controllers/tunnel/tunnel_test.go
  pkg/gateway/gateway_test.go
Labels: ready-to-test

#3341 Don't re-allocate global IP if retrieval of internal service fails
  pkg/globalnet/controllers/base_controllers.go
  pkg/globalnet/controllers/cluster_egressip_controller_test.go
  pkg/globalnet/controllers/controllers_suite_test.go
  pkg/globalnet/controllers/global_egressip_controller_test.go
  pkg/globalnet/controllers/global_ingressip_controller.go
  pkg/globalnet/controllers/global_ingressip_controller_test.go
Labels: backport, release-note-needed, ready-to-test

#3339 Configure packefilter driver via ConfigMap setting
  go.mod
  go.sum
  pkg/globalnet/main.go
  pkg/packetfilter/configure/configure.go
  pkg/packetfilter/configure/configure_suite_test.go
  pkg/packetfilter/packetfilter.go
  pkg/routeagent_driver/main.go
Labels: ready-to-test

#3344 Automated backport of #3343: Don't re-allocate allocated IP if retrieval of internal
  pkg/globalnet/controllers/base_controllers.go
  pkg/globalnet/controllers/cluster_egressip_controller_test.go
  pkg/globalnet/controllers/controllers_suite_test.go
  pkg/globalnet/controllers/global_egressip_controller_test.go
  pkg/globalnet/controllers/global_ingressip_controller.go
  pkg/globalnet/controllers/global_ingressip_controller_test.go
Labels: release-note-needed, ready-to-test, automated-backport, release-note-handled

#3350 Packetfilter API: add support for IPv6
  pkg/globalnet/controllers/gateway_monitor.go
  pkg/globalnet/controllers/gateway_monitor_test.go
  pkg/globalnet/controllers/packetfilter/iface.go
  pkg/globalnet/controllers/uninstall.go
  pkg/packetfilter/adapter_test.go
  pkg/packetfilter/fake/driver.go
  pkg/packetfilter/fake/namedset.go
  pkg/packetfilter/fake/packetfilter.go
  pkg/packetfilter/iptables/iptables.go
  pkg/packetfilter/iptables/namedset.go
  pkg/packetfilter/nftables/namedset.go
  pkg/packetfilter/nftables/nftables.go
  pkg/packetfilter/nftables/nftables_test.go
  pkg/packetfilter/packetfilter.go
  pkg/routeagent_driver/handlers/kubeproxy/kp_packetfilter.go
  pkg/routeagent_driver/handlers/kubeproxy/uninstall.go
  pkg/routeagent_driver/handlers/mtu/mtuhandler.go
  pkg/routeagent_driver/handlers/ovn/handler.go
Labels: ready-to-test

#3345 Add tunnel controller unit tests for dual-stack Endpoint removal
  pkg/controllers/tunnel/tunnel_test.go
Labels: ready-to-test

#3329 Add IP family support to Libreswan driver
  pkg/apis/submariner.io/v1/endpoint.go
  pkg/apis/submariner.io/v1/endpoint_test.go
  pkg/cable/libreswan/libreswan.go
  pkg/cable/libreswan/libreswan_internal_test.go
Labels: ready-to-test

#3358 Fix data race in gateway
  pkg/gateway/gateway.go
Labels: ready-to-test

#3367 Automated backport of #3358: Fix data race in gateway
  pkg/gateway/gateway.go
Labels: ready-to-test

#3366 Automated backport of #3358: Fix data race in gateway
  pkg/gateway/gateway.go
Labels: ready-to-test, automated-backport

#3362 Enable storing CIDR elements in nftables sets
  pkg/packetfilter/nftables/namedset.go
  pkg/packetfilter/nftables/nftables_test.go
Labels: ready-to-test

#3354 Add nftables e2e tests
  .github/workflows/e2e.yml
Labels: ready-to-test

#3369 Implement IPv6 health check IP resolution
  pkg/cable/vxlan/vxlan.go
  pkg/cable/vxlan/vxlan_test.go
  pkg/cni/cni_iface.go
  pkg/cni/cni_iface_test.go
  pkg/cni/cni_suite_test.go
  pkg/endpoint/local_endpoint.go
  pkg/endpoint/local_endpoint_test.go
  pkg/endpoint/public_ip_watcher_test.go
  pkg/globalnet/controllers/controllers_suite_test.go
  pkg/globalnet/controllers/gateway_monitor.go
  pkg/routeagent_driver/handlers/kubeproxy/kp_packetfilter.go
  pkg/routeagent_driver/handlers/kubeproxy/sync_handler_test.go
  pkg/types/types.go
Labels: ready-to-test

#3370 Ignore .tekton in YAMLlint
  .yamllint.yml
Labels: ready-to-test
