Repository submariner-io/submariner, pull requests merged in 2025-02, with the labels that each got.

#3291 E2E: Use GetHealthCheckIP in gateway status test
  test/e2e/dataplane/gateway_status.go
Labels: ready-to-test

#3296 Remove AddToScheme call in event controller New
  pkg/event/controller/controller.go
Labels: ready-to-test

#3293 Update K8s versions tested in E2E
  .github/workflows/e2e.yml
  .github/workflows/flake_finder.yml
Labels: ready-to-test

#3313 Remove unused nolint:gosec directive in libreswan.go
  pkg/cable/libreswan/libreswan.go
Labels: ready-to-test

#3312 Return slice from GetIPFamilies instead of fixed-sized array
  pkg/types/types.go
Labels: backport, ready-to-test

#3314 Automated backport of #3312: Return slice from GetIPFamilies instead of fixed-sized array
  pkg/types/types.go
Labels: ready-to-test, automated-backport

#3318 Add unit tests in tunnel to cover IPv6/dual-stack
  pkg/cableengine/cableengine.go
  pkg/controllers/tunnel/tunnel_test.go
Labels: ready-to-test

#3317 Add unit tests in cidr package to increase coverage
  pkg/cidr/cidr_test.go
Labels: ready-to-test
